

foreach x in `1' {
replace `x' = lower(`x')
replace `x' = subinstr(`x'," ","",.)


replace `x'="%" if inlist(`x',"percent")
replace `x'="%{WBCs}" if inlist(`x',"percentoftotalleukocytes")
replace `x'="%{normal}" if inlist(`x',"%ofnormal")
replace `x'="1/2cup" if inlist(`x',"1fruit,1/2cupor5dried","1earor1/2cup","1/2cupor2-4sticks","1fruitor1/2cup","1/2fruitor1/2cup","1/2cupvegetables,or1cupofsoup","1/2cupofcarrotsor2-3oz.ofjuice")
replace `x'="10*3/mm3" if inlist(`x',"10^3/mm3","103/mm3","x1000/mm3","th/cmm")
replace `x'="10*3/uL" if inlist(`x',"10^3cells/ul","103/mm3","thousands/ul","x10^3/ul","thousandspermicroliter","x10e3/ul","thou/ul(thousandspermicroliter)","10^3/ul")
replace `x'="10*6/mm3" if inlist(`x',"106/mm3","m/cmm","10^6/mm3")
replace `x'="10*6/uL" if inlist(`x',"count,x10e12","millions/ul","x10e6/ul","10^6/ul")
replace `x'="10*9/L" if inlist(`x',"10^9/l","count,x10e9")
replace `x'="3-4oz" if inlist(`x',"3-4oz.")
replace `x'="Cel" if inlist(`x',"c")
replace `x'="L" if inlist(`x',"litres","liters","l")
replace `x'="[IU]" if inlist(`x',"i.u.","iu")
replace `x'="[IU]/L" if inlist(`x',"iu/l","u/l")
replace `x'="[IU]/dL" if inlist(`x',"iu/dl")
replace `x'="[IU]/mL" if inlist(`x',"iu/ml")
replace `x'="[cup_us]" if inlist(`x',"cup")
replace `x'="[ft_us]" if inlist(`x',"feet","ft")
replace `x'="[hnsf'U]" if inlist(`x',"hu","hounsfieldunits(hu)")
replace `x'="[in_us]" if inlist(`x',"inches","inchestonextlower1/4inch","tonextlower1/4inch","inches,tonextlower1/4inch","in")
replace `x'="[lb_av]" if inlist(`x',"lbs","pounds,tonearestpound","lb","pounds")
replace `x'="[oz_av]" if inlist(`x',"oz","1oz.or1/2cup","3-4oz","1oz")
replace `x'="[pH]" if inlist(`x',"ph")
replace `x'="[tbs_us]" if inlist(`x',"1tbs","tbs")
replace `x'="a" if inlist(`x',"years","year","yearsold","numberofyearssinceexam1")
replace `x'="agatstonunit" if inlist(`x',"Agatston unit")
replace `x'="cm" if inlist(`x',"centimeters")
replace `x'="cs" if inlist(`x',"hundredthsofsecond","hundredthsofasec.","hundredsofsecond","hundredthsofasecond")
replace `x'="d" if inlist(`x',"days","dayssinceexam1","numberofdayssinceexam1")
replace `x'="dL" if inlist(`x',"deciliter","dl")
replace `x'="dg/dL" if inlist(`x',"dg/dl","decigrams/100ml")
replace `x'="fL" if inlist(`x',"femtoliter","fl")
replace `x'="g" if inlist(`x',"gm")
replace `x'="g/d" if inlist(`x',"g/day","g/24hr")
replace `x'="g/dL" if inlist(`x',"gm/dl","g/dl")
replace `x'="h" if inlist(`x',"hrs","hours","hr","hour")
replace `x'="mL" if inlist(`x',"ml")
replace `x'="mL/d" if inlist(`x',"ml/alcohol/day","ml/day")
replace `x'="mL/min/{1.73_m2}" if inlist(`x',"ml/minper1.73m2","ml/min/1.73m2","ml/min/1.73m^2")
replace `x'="mL/s" if inlist(`x',"ml/sec")
replace `x'="m[IU]/L" if inlist(`x',"mul","mu/l","miu/l")
replace `x'="m[IU]/mL" if inlist(`x',"mu/ml","miu/ml")
replace `x'="meq/L" if inlist(`x',"meq/liter","meq/l")
replace `x'="meq/L(x100)" if inlist(`x',"meq/liter(x100)","meq/l(x100)")
replace `x'="mg/L" if inlist(`x',"mg/l","mg/lfeu")
replace `x'="mg/L{FEU}" if inlist(`x',"mg/lfeu")
replace `x'="mg/d" if inlist(`x',"mg/24hours","mg/24hr","mg/day")
replace `x'="mg/dL" if inlist(`x',"mg/100ml","mg/dl","mgper100ml","mgperdl")
replace `x'="mg/g" if inlist(`x',"mg/gcr")
replace `x'="mg/mL" if inlist(`x',"mg/ml")
replace `x'="min" if inlist(`x',"minutes")
replace `x'="mm/h" if inlist(`x',"mm/hr")
replace `x'="mm3(10*3/uL)" if inlist(`x',"mm3(1,000,000permicroliter)","mm3(1,000,000/microliter)","mm3(10^3/ul)")
replace `x'="mm[Hg]" if inlist(`x',"tonearest2mm/hg","mm/hg","hgmm","tonearest2mmhg","mmhg")
replace `x'="mmol/L" if inlist(`x',"mmolperl","mmol/l")
replace `x'="mmol/dL" if inlist(`x',"mmoles/dl","mmol/dl")
replace `x'="mo" if inlist(`x',"month","months")
replace `x'="ms" if inlist(`x',"milliseconds","millisec","msec")
replace `x'="ng/L" if inlist(`x',"ng/l")
replace `x'="ng/mL" if inlist(`x',"plasmang/ml","ng/ml")
replace `x'="nmol/min/mL" if inlist(`x',"nmol/min/ml")
replace `x'="none" if inlist(`x',"agatstonunit","n/a","numberofsiblings","codes","scale","score","numberofkids")
replace `x'="pg/mL" if inlist(`x',"pg/ml")
replace `x'="pg/{cell}" if inlist(`x',"pg/cell")
replace `x'="pmol/L" if inlist(`x',"pmol/l")
replace `x'="s" if inlist(`x',"seconds")
replace `x'="uV" if inlist(`x',"uv","microvolts")
replace `x'="u[IU]/mL" if inlist(`x',"uiu/ml","uu/ml","microu/ml")
replace `x'="ug/L" if inlist(`x',"mcg/l","ug/l")
replace `x'="ug/dL" if inlist(`x',"ug/dl")
replace `x'="ug/mL" if inlist(`x',"ug/ml")
replace `x'="um3" if inlist(`x',"microm3","um3(micrometerscubed)")
replace `x'="{#}/d" if inlist(`x',"num/day")
replace `x'="{#}/mL" if inlist(`x',"platelets/ml","num/ml")
replace `x'="{#}/uL" if inlist(`x',"number/microl","num/ul")
replace `x'="{beats}/min" if inlist(`x',"beats","beatsperminute","beats/minute","bpm","beatspermin","beats/min")
replace `x'="{breath}/min" if inlist(`x',"breaths/min")
replace `x'="{cells}/uL" if inlist(`x',"kcell/mcl","cells/ul","kcell/ul")
replace `x'="{cigarettes}/d" if inlist(`x',"cigarettes/day","cigarettesperday","cigarette/day")
replace `x'="{events}/h" if inlist(`x',"events/hr","events/hour","#/hr")
replace `x'="{ratio}" if inlist(`x',"ratio")
replace `x'="{servings}" if inlist(`x',"drinks","1serving","servings")
replace `x'="{servings}/d" if inlist(`x',"servings/day")
replace `x'="{servings}/wk" if inlist(`x',"servingsperweek","drinks/week","servings/week")





replace `x'="" if inlist(`x',"none")
}



/* add this codeline if need be

replace `x'="" if inlist(`x',"none")