#!/usr/bin/env python3
"""HV-Lint Phase 3: Semantic validation using extended PHV detail index.

Validates that YAML transformation files are semantically consistent
with the dbGaP FTP data dictionaries. Requires the extended detail
index generated by build_phv_detail_index.py.

Checks:
    3.9   value_mappings completeness -- source codes in dbGaP but absent
          from value_mappings are flagged (silent data loss)
    3.10  PHV type vs slot role, at any depth -- an enum slot (status, sex, race, ...) fed by a
          bare variable with no value_mappings; a numeric slot fed by a variable with category
          codes
    3.12  PHV description vs concept domain -- variable description keywords
          should not conflict with the file's clinical domain
    3.13  Condition null-default risk -- Condition blocks whose visit case
          routes to phases where condition_status PHV is not collected
          (null -> false ABSENT)
    3.14  unit_conversion source_unit mismatch -- unit_conversion source_unit
          must match the dbGaP-declared unit for the source PHV
    3.15  Phantom code detection -- value_mappings keys that don't exist in
          dbGaP coded values (typo, cross-cohort copy-paste, version drift)
    3.16  Quantity missing unit -- a measured value (value_decimal / value_integer) with no
          unit, at any depth (ERROR; UNITLESS_OBSERVATION_TYPES is the allowlist)

Usage:
    python hv-lint/phase-3/validate_semantic.py --cache-dir hv-lint/dbgap-cache
    python hv-lint/phase-3/validate_semantic.py --cache-dir hv-lint/dbgap-cache --cohort HCHS
"""

from __future__ import annotations

import argparse
import gzip
import json
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from _paths import find_transform_dir  # noqa: E402
import _known_issues  # noqa: E402
import _cohorts  # noqa: E402
from _derivations import iter_nested_class_derivs, walk_slot_derivations  # noqa: E402
sys.path.insert(0, str(Path(__file__).resolve().parent))
import check_status_semantic as _css  # noqa: E402  (stats reader and follow-up detector)




# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------


SEVERITY_RANK = {"CRITICAL": 5, "ERROR": 4, "HIGH": 3, "WARNING": 2, "INFO": 1}

PHV_RE = re.compile(r"phv\d{8}")

# Rule 3.9: Known skip-label patterns for coded values that are
# legitimately omitted from value_mappings.
SKIP_LABEL_RE = re.compile(
    r"unknown|refuse|don.t know|do not know|missing|N/?A|not applicable|"
    r"not recorded|no response|not assessed|blank",
    re.IGNORECASE,
)

# Rule 3.9: High-impact slots where missing coded values are virtually
# always bugs (real data silently lost), not intentional omissions.
# Missing codes in these slots are elevated from WARNING to ERROR.
# NOTE: ethnicity excluded -- frequently shares a PHV with race, so
# race-category codes would be false-positive ERRORs on ethnicity.
HIGH_IMPACT_SLOTS = {
    "race", "annotated_sex", "sex", "ethnicity",
    "condition_status", "exposure_status", "procedure_status", "value_enum",
}

# Rule 3.9 severity by the share of observed rows a block drops (#784 addendum 5-7): ERROR from
# half the rows on a high-impact slot, WARNING from a tenth, INFO below. Declared-code fallbacks
# (no var_report counts) are capped at WARNING because nothing says the code occurs.
LOST_SHARE_ERROR = 0.5
LOST_SHARE_WARNING = 0.1

# Severity codes that mean "no severity": leaving them unmapped is correct.
_NO_SEVERITY_RE = re.compile(r"^\s*(none|no\b|no copd|normal)", re.IGNORECASE)

# The two slots that commonly read one PHV between them; a code mapped by the sibling is used.
_SIBLING_SLOTS = {"race": "ethnicity", "ethnicity": "race"}

# Rule 3.10: Slot role -> expected dbGaP type mapping.
# Slots whose semantic role implies a specific data type.
ENUM_SLOTS = {
    "condition_status", "exposure_status", "procedure_status",
    "annotated_sex", "race", "ethnicity", "vital_status",
}
NUMERIC_SLOTS = {
    "value_decimal", "value_integer",
}

# Rule 3.12: Domain conflict pairs.
# If a file's domain keywords contain terms from column A,
# a PHV description containing terms from column B is flagged.
DOMAIN_CONFLICTS: list[tuple[set[str], set[str]]] = [
    ({"coronary", "heart", "cardiac", "myocardial"},
     {"carotid", "neck", "cerebral", "cerebrovascular"}),
    ({"carotid", "neck", "cerebral", "cerebrovascular"},
     {"coronary", "heart", "cardiac", "myocardial"}),
    ({"systolic"}, {"diastolic"}),
    ({"diastolic"}, {"systolic"}),
    ({"urine", "urinary"}, {"serum", "plasma", "blood"}),
    ({"serum", "plasma"}, {"urine", "urinary"}),
    ({"arm", "brachial"}, {"leg", "ankle", "pedal"}),
    ({"leg", "ankle"}, {"arm", "brachial"}),
    ({"fasting"}, {"postprandial", "random", "non-fasting"}),
    ({"lymphocyte"}, {"leukocyte", "white blood", "wbc", "neutrophil", "monocyte"}),
    ({"leukocyte", "white blood", "wbc"}, {"lymphocyte", "platelet", "red blood", "rbc"}),
    ({"platelet"}, {"white blood", "wbc", "leukocyte", "red blood", "rbc"}),
    ({"hemoglobin", "hgb"}, {"hematocrit", "platelet"}),
    ({"glucose"}, {"insulin", "creatinine", "cholesterol"}),
    ({"creatinine"}, {"glucose", "cholesterol", "triglyceride"}),
    ({"cholesterol", "ldl"}, {"triglyceride", "glucose", "creatinine"}),
    ({"triglyceride"}, {"cholesterol", "ldl", "hdl", "glucose"}),
    ({"height"}, {"weight", "bmi"}),
    ({"weight"}, {"height"}),
]

# ---------------------------------------------------------------------------
# Data Structures
# ---------------------------------------------------------------------------


@dataclass
class PhvDetail:
    """Per-variable metadata from the extended FTP index."""
    name: str
    pht: str
    type: str
    unit: str | None
    description: str
    codes: dict[str, str] | None
    coll_interval: str | None = None


@dataclass
class DetailIndex:
    """Extended PHV detail index for a single cohort."""
    records: dict[str, PhvDetail] = field(default_factory=dict)


@dataclass
class Finding:
    file: str
    block: int
    check: str
    severity: str
    message: str

    def terminal_line(self) -> str:
        sev = self.severity[:5].ljust(5)
        return f"  {sev}  block {self.block:>3}  [{self.check}] {self.message}"

    def gh_annotation(self) -> str:
        level = {
            "CRITICAL": "error", "ERROR": "error", "HIGH": "warning",
            "WARNING": "warning", "INFO": "notice",
        }.get(self.severity, "notice")
        file_esc = (self.file.replace("%", "%25").replace("\r", "%0D")
                    .replace("\n", "%0A").replace(":", "%3A").replace(",", "%2C"))
        msg_esc = self.message.replace("%", "%25").replace("\r", "%0D").replace("\n", "%0A")
        return f"::{level} file={file_esc}::HV-Lint [{self.check}] {msg_esc} (block {self.block})"


# ---------------------------------------------------------------------------
# Index Loading
# ---------------------------------------------------------------------------


def load_detail_index(cache_dir: Path, cache_key: str) -> DetailIndex:
    """Load the extended detail index for a cohort."""
    gz_path = cache_dir / f"{cache_key}_detail.json.gz"
    json_path = cache_dir / f"{cache_key}_detail.json"

    if gz_path.exists():
        with gzip.open(gz_path, "rt", encoding="utf-8") as f:
            raw = json.load(f)
    elif json_path.exists():
        with json_path.open(encoding="utf-8") as f:
            raw = json.load(f)
    else:
        raise FileNotFoundError(
            f"No detail index for '{cache_key}': expected {gz_path} or {json_path}"
        )

    idx = DetailIndex()
    for phv, rec in raw.items():
        idx.records[phv] = PhvDetail(
            name=rec.get("name", ""),
            pht=rec.get("pht", ""),
            type=rec.get("type", ""),
            unit=rec.get("unit"),
            description=rec.get("description", ""),
            codes=rec.get("codes"),
            coll_interval=rec.get("coll_interval"),
        )
    return idx


# ---------------------------------------------------------------------------
# File Discovery
# ---------------------------------------------------------------------------


def find_yaml_files(base_dir: Path, cohort: str) -> list[Path]:
    files = sorted(
        f for f in base_dir.rglob("*.yaml")
        if any("-ingest" in part for part in f.parts)
        and not f.name.endswith(".swp")
    )
    if cohort.lower() != "all":
        pattern = f"{cohort}-ingest".lower()
        files = [f for f in files if any(part.lower() == pattern for part in f.parts)]
    return files


def detect_cohort(file_path: Path) -> str:
    for part in file_path.parts:
        if part.endswith("-ingest"):
            return part.replace("-ingest", "")
    return "UNKNOWN"


# ---------------------------------------------------------------------------
# Utility: Extract domain keywords from filename
# ---------------------------------------------------------------------------

def _filename_domain_keywords(filename: str) -> set[str]:
    """Extract domain keywords from a YAML filename.

    E.g., "hist_cor_angio.yaml" -> {"hist", "cor", "coronary", "angio", "angioplasty"}
    """
    stem = filename.replace(".yaml", "").replace("_", " ").lower()
    words = set(stem.split())

    # Expand common abbreviations used in HV filenames
    expansions: dict[str, list[str]] = {
        "cor": ["coronary"],
        "angio": ["angioplasty", "angiography"],
        "sys": ["systolic"],
        "dia": ["diastolic"],
        "bp": ["blood", "pressure"],
        "bdy": ["body"],
        "hgt": ["height"],
        "wgt": ["weight"],
        "bmi": ["bmi"],
        "cig": ["cigarette", "smoking"],
        "smok": ["smoking"],
        "chol": ["cholesterol"],
        "trig": ["triglyceride"],
        "glu": ["glucose"],
        "creat": ["creatinine"],
        "cyst": ["cystatin"],
        "cysc": ["cystatin"],
        "lympho": ["lymphocyte"],
        "leuko": ["leukocyte"],
        "wbc": ["white blood", "leukocyte", "wbc"],
        "rbc": ["red blood"],
        "plt": ["platelet"],
        "hemo": ["hemoglobin"],
        "hgb": ["hemoglobin"],
        "hct": ["hematocrit"],
        "afib": ["atrial", "fibrillation"],
        "pad": ["peripheral", "arterial"],
        "copd": ["copd", "pulmonary", "obstructive"],
        "stroke": ["stroke", "cerebrovascular"],
        "hyperten": ["hypertension", "blood pressure"],
        "diab": ["diabetes"],
        "insulin": ["insulin"],
        "ct": ["count"],
    }
    expanded = set(words)
    for w in words:
        if w in expansions:
            expanded.update(expansions[w])

    return expanded


# ---------------------------------------------------------------------------
# Check 3.9: value_mappings Completeness
# ---------------------------------------------------------------------------


def observed_values(stats, pf: str) -> dict[str, int] | None:
    """``{value: rows}`` observed for ``pf`` in the var_report, or None when it has no counts."""
    if not stats or pf not in stats:
        return None
    return {str(k): int(v) for k, v in stats[pf].counts.items() if int(v) > 0}


def _vm_slots(block: dict):
    """Every slot (any depth) whose values come from ``value_mappings`` on one PHV, no expr."""
    for site in walk_slot_derivations(block):
        sd = site.slot_def
        vm = sd.get("value_mappings")
        if not isinstance(vm, dict) or not vm or sd.get("expr"):
            continue
        pf = sd.get("populated_from")
        if isinstance(pf, str) and PHV_RE.fullmatch(pf):
            yield site, pf, vm


def _sibling_mapped(block: dict, site, pf: str) -> set[str]:
    """Keys mapped by the race/ethnicity sibling of ``site`` from the same PHV."""
    sib = _SIBLING_SLOTS.get(site.slot_name)
    if not sib:
        return set()
    for other, opf, ovm in _vm_slots(block):
        if other.slot_name == sib and opf == pf and other.class_name == site.class_name:
            return {str(k) for k in ovm}
    return set()


def check_value_mappings_completeness(
    block: dict, block_idx: int, rel_path: str,
    detail_idx: DetailIndex,
    stats: dict | None = None,
    followup_idx=None,
) -> list[Finding]:
    """Check 3.9: values the source holds that ``value_mappings`` drops (silent data loss).

    The universe is the var_report's OBSERVED values (``stats``); declared codes are a fallback
    capped at WARNING, and a PHV with neither is reported at INFO as not validatable. A declared
    code no row carries loses nothing; a value written as its label (JHS) is mapped when the
    label is a key. Not reported: the negative answer of a conditional follow-up question (its
    "No" is not "no condition", the defect 3.18 rejects), a code the race/ethnicity sibling slot
    maps from the same PHV, and a severity code labelled none/no. Severity scales with the share
    of observed rows dropped.
    """
    findings: list[Finding] = []
    for site, pf, vm in _vm_slots(block):
        cls_name, slot_name = site.class_name, site.slot_name
        detail = detail_idx.records.get(pf)
        declared = (detail.codes or {}) if detail else {}
        observed = observed_values(stats, pf)
        keys = {str(k) for k in vm}

        if observed is not None:
            universe, basis = observed, "observed"
        elif declared:
            universe, basis = {c: 0 for c in declared}, "declared"
        else:
            findings.append(Finding(
                rel_path, block_idx, "3.9", "INFO",
                f"value_mappings on {cls_name}.{slot_name} ({pf}) could not be validated -- "
                f"no coded values in the data dictionary or the var_report",
            ))
            continue

        def _label(code: str) -> str:
            return str(declared.get(code, "")) if declared else ""

        missing = []
        for code in sorted(universe):
            if code in keys or (_label(code) and _label(code) in keys):
                continue
            missing.append(code)
        if not missing:
            continue

        followup = None
        if slot_name == "condition_status" and followup_idx is not None:
            followup = _css.detect_followup(pf, followup_idx, stats)
        sibling = _sibling_mapped(block, site, pf)
        total = sum(universe.values()) or 0
        observed_drops: list[Finding] = []

        for code in missing:
            label = _label(code)
            rows = universe.get(code, 0)
            if code in sibling:
                continue
            if followup is not None and _css.classify_label(label, code) == "negative":
                continue
            if slot_name.endswith("_severity") and _NO_SEVERITY_RE.match(label or code):
                continue
            where = f"value_mappings on {cls_name}.{slot_name} ({pf})"
            what = f"'{code}'" + (f' ("{label}")' if label else "")
            if label and SKIP_LABEL_RE.search(label):
                findings.append(Finding(
                    rel_path, block_idx, "3.9", "INFO",
                    f"{where} drops {basis} code {what}"
                    + (f", {rows:,} rows" if basis == "observed" else "")
                    + " -- likely intentional skip",
                ))
                continue
            if basis == "observed":
                share = rows / total if total else 0.0
                if share >= LOST_SHARE_ERROR and slot_name in HIGH_IMPACT_SLOTS:
                    sev = "ERROR"
                elif share >= LOST_SHARE_WARNING:
                    sev = "WARNING"
                else:
                    sev = "INFO"
                observed_drops.append(Finding(
                    rel_path, block_idx, "3.9", sev,
                    f"{where} drops observed value {what}: {rows:,} of {total:,} rows "
                    f"({share:.0%}) emit no value -- possible data loss",
                ))
            else:
                findings.append(Finding(
                    rel_path, block_idx, "3.9", "WARNING",
                    f"{where} omits declared code {what}; no var_report counts, so whether any "
                    f"row carries it is unknown",
                ))
        findings.extend(_escalate_by_slot(observed_drops, universe, total, slot_name))
    return findings


_RANK = {"INFO": 0, "WARNING": 1, "ERROR": 2}
_DROP_RE = re.compile(r"drops observed value '([^']*)'")


def _escalate_by_slot(drops: list[Finding], universe: dict, total: int,
                      slot_name: str) -> list[Finding]:
    """3.9 severity also follows the rows the SLOT loses over all its reported codes.

    When no single code reaches the tier the slot's total does (three codes of 20% each on a
    high-impact slot), the largest dropped code is raised to that tier and says so. Only the
    largest one: raising every 1-row code with it would bury the finding that matters.
    """
    if not drops or not total:
        return drops
    rows = [universe.get(_DROP_RE.search(f.message).group(1), 0) for f in drops]
    lost = sum(rows)
    share = lost / total
    tier = ("ERROR" if share >= LOST_SHARE_ERROR and slot_name in HIGH_IMPACT_SLOTS
            else "WARNING" if share >= LOST_SHARE_WARNING else "INFO")
    if max(_RANK[f.severity] for f in drops) >= _RANK[tier]:
        return drops
    top = max(zip(rows, (f.message for f in drops), drops), key=lambda x: (x[0], x[1]))[2]
    top.severity = tier
    top.message += (f"; with the slot's other dropped codes, {lost:,} of {total:,} rows "
                    f"({share:.0%}) are lost")
    return drops


# ---------------------------------------------------------------------------
# Check 3.10: PHV Type <-> Slot Role Compatibility
# ---------------------------------------------------------------------------


def check_phv_type_compatibility(
    block: dict, block_idx: int, rel_path: str,
    detail_idx: DetailIndex,
) -> list[Finding]:
    """Check 3.10: Flag PHVs whose dbGaP type conflicts with slot role.

    Walks every slot at every depth: all ``value_decimal`` / ``value_integer`` slots are nested
    inside a Quantity, so a top-level walk never reaches the numeric branch.
    """
    findings: list[Finding] = []
    for site in walk_slot_derivations(block):
        cls_name, slot_name, slot_def = site.class_name, site.slot_name, site.slot_def

        # Only check bare populated_from (no expr wrapping)
        pf = slot_def.get("populated_from")
        if not isinstance(pf, str) or not PHV_RE.fullmatch(pf):
            continue
        # Skip if expr is present -- the expression handles conversion
        if slot_def.get("expr"):
            continue
        # Skip if value_mappings -- the mappings handle type conversion
        if slot_def.get("value_mappings"):
            continue

        detail = detail_idx.records.get(pf)
        if not detail:
            continue

        vtype = detail.type.lower()  # e.g., "encoded value", "decimal", "integer"
        unit = (detail.unit or "").lower()

        # An enum slot fed by a bare variable with no value_mappings writes the raw value into
        # the enum, whatever its dbGaP type: ARIC carotid_plaque b0 wrote V1AGE01 (an age,
        # type string) into condition_status. Status slots and the demographic enums are
        # checked; a status variable's raw codes are never enum names either.
        if slot_name in ENUM_SLOTS:
            suggestion = _suggest_adjacent(
                detail_idx, detail.pht, detail.name,
                {"encoded value", "encoded"},
            )
            msg = (
                f"{cls_name}.{slot_name} populated_from "
                f"{pf} ({detail.name}) has type '{detail.type}'"
            )
            if "day" in unit:
                msg += f" with unit '{detail.unit}'"
            msg += (" written straight into an enum slot with no value_mappings -- its raw "
                    "values are not enum members")
            if suggestion:
                msg += f". Did you mean {suggestion}?"
            findings.append(Finding(
                file=rel_path,
                block=block_idx,
                check="3.10",
                severity="ERROR",
                message=msg,
            ))

        # A numeric slot fed by a category-coded variable emits the CODE as a measurement
        # (WHI sleep: code 4, "8-9 hours", becomes 4 h). A code list of 2+ is what makes it
        # categorical; an 'encoded' type with no codes (CARDIA C42CHOUR) is a plain number.
        if slot_name in NUMERIC_SLOTS:
            if vtype in ("encoded value", "encoded") and len(detail.codes or {}) >= 2:
                suggestion = _suggest_adjacent(
                    detail_idx, detail.pht, detail.name,
                    {"decimal", "integer", "num"},
                )
                msg = (
                    f"{cls_name}.{slot_name} populated_from "
                    f"{pf} ({detail.name}) has type '{detail.type}'"
                    f" and {len(detail.codes or {})} category codes -- the code, not a "
                    f"measurement, is emitted"
                )
                if suggestion:
                    msg += f". Did you mean {suggestion}?"
                findings.append(Finding(
                    file=rel_path,
                    block=block_idx,
                    check="3.10",
                    severity="ERROR",
                    message=msg,
                ))

    return findings


def _suggest_adjacent(
    detail_idx: DetailIndex, pht: str, var_name: str,
    compatible_types: set[str],
) -> str | None:
    """Search for a nearby PHV in the same PHT with a compatible type.

    Looks for variables with a name that shares a prefix with the target.
    """
    if not pht or not var_name:
        return None

    # Extract a prefix to match against (first chars before trailing digits)
    prefix = re.sub(r"\d+$", "", var_name)
    if len(prefix) < 2:
        return None

    candidates = []
    for phv, rec in detail_idx.records.items():
        if rec.pht != pht:
            continue
        if rec.name == var_name:
            continue
        if rec.type.lower() not in compatible_types:
            continue
        if rec.name.startswith(prefix):
            candidates.append((phv, rec.name))

    if not candidates:
        return None

    # Return the best match (shortest name difference)
    candidates.sort(key=lambda x: abs(len(x[1]) - len(var_name)))
    phv, name = candidates[0]
    return f"{phv} ({name}, type: {detail_idx.records[phv].type})"


# ---------------------------------------------------------------------------
# Check 3.12: PHV Description <-> Domain Mismatch
# ---------------------------------------------------------------------------


def check_phv_domain_mismatch(
    block: dict, block_idx: int, rel_path: str,
    detail_idx: DetailIndex,
    file_domain: set[str],
) -> list[Finding]:
    """Check 3.12: Flag PHVs whose description conflicts with file domain."""
    findings: list[Finding] = []
    if not file_domain:
        return findings

    class_derivs = block.get("class_derivations")
    if not isinstance(class_derivs, dict):
        return findings

    for cls_name, cls_def in class_derivs.items():
        if not isinstance(cls_def, dict):
            continue
        slot_derivs = cls_def.get("slot_derivations")
        if not isinstance(slot_derivs, dict):
            continue

        for slot_name, slot_def in slot_derivs.items():
            if not isinstance(slot_def, dict):
                continue

            # Collect all PHV refs in this slot
            phvs: list[str] = []
            pf = slot_def.get("populated_from")
            if isinstance(pf, str) and PHV_RE.fullmatch(pf):
                phvs.append(pf)
            expr = slot_def.get("expr")
            if isinstance(expr, str):
                phvs.extend(m.group() for m in PHV_RE.finditer(expr))

            for phv in phvs:
                detail = detail_idx.records.get(phv)
                if not detail:
                    continue

                desc_lower = detail.description.lower()
                desc_words = set(re.findall(r"[a-z]+", desc_lower))

                for domain_a, conflict_b in DOMAIN_CONFLICTS:
                    # Check if file domain overlaps with domain_a
                    if not (file_domain & domain_a):
                        continue
                    # Check if PHV description contains conflict_b terms
                    matched_conflicts = desc_words & conflict_b
                    # Also check multi-word conflict terms
                    for term in conflict_b:
                        if " " in term and term in desc_lower:
                            matched_conflicts.add(term)

                    if matched_conflicts:
                        findings.append(Finding(
                            file=rel_path,
                            block=block_idx,
                            check="3.12",
                            severity="WARNING",
                            message=(
                                f"{cls_name}.{slot_name}: {phv} "
                                f"({detail.name}) description "
                                f"\"{detail.description[:80]}\" contains "
                                f"domain keyword(s) "
                                f"{sorted(matched_conflicts)} -- "
                                f"conflicts with file domain "
                                f"{sorted(file_domain & domain_a)}"
                            ),
                        ))
                        break  # One conflict per PHV is enough

    return findings


# ---------------------------------------------------------------------------
# Check 3.14: unit_conversion Source Unit Mismatch
# ---------------------------------------------------------------------------

# UCUM <-> dbGaP informal unit equivalences.
# Keys: UCUM notation used in YAML source_unit.
# Values: set of equivalent dbGaP unit strings (case-insensitive match).
_UCUM_TO_DBGAP: dict[str, set[str]] = {
    "[lb_av]": {"lb", "lbs", "pounds", "pound"},
    "[in_us]": {"in", "inches", "inch"},
    "[in_i]":  {"in", "inches", "inch"},
    "kg":      {"kg", "kilograms", "kilogram"},
    "cm":      {"cm", "centimeters", "centimeter"},
    "m":       {"m", "meters", "meter"},
    "mm[Hg]":  {"mmhg", "mm hg", "mm(hg)"},
    "mg/dL":   {"mg/dl"},
    "g/dL":    {"g/dl"},
    "mg":      {"mg"},
    "g":       {"g", "gm", "grams", "gram"},
    "mL":      {"ml", "milliliters"},
    "L":       {"l", "liters", "liter"},
    "mm":      {"mm"},
    "%":       {"%", "percent"},
    "ms":      {"ms", "msec", "milliseconds"},
    "s":       {"seconds", "sec", "s"},
    "min":     {"min", "minutes"},
    "d":       {"days", "day", "d"},
    "a":       {"years", "year", "yr"},
    "mo":      {"months", "month"},
    "u[IU]/mL": {"uiu/ml", "uiu/ml", "iu/ml", "miu/ml"},
    "10*3/uL": {"10*3/ul", "1000/ul", "k/ul", "10^3/ul"},
}


def _units_compatible(ucum_unit: str, dbgap_unit: str) -> bool:
    """Check if a UCUM source_unit is compatible with a dbGaP declared unit.

    Returns True if they match (meaning the conversion IS consistent
    with the source unit), or if we can't determine compatibility.
    """
    if not ucum_unit or not dbgap_unit:
        return True  # Can't check -- don't flag

    ucum_clean = ucum_unit.strip().strip("'\"")
    dbgap_lower = dbgap_unit.strip().lower()

    # Direct match (case-insensitive)
    if ucum_clean.lower() == dbgap_lower:
        return True

    # Look up UCUM equivalences
    equivalents = _UCUM_TO_DBGAP.get(ucum_clean)
    if equivalents and dbgap_lower in equivalents:
        return True

    # Reverse check: if dbGaP unit matches the UCUM target_unit, that's
    # a MISMATCH (source is already in target units, conversion is wrong).
    # This case is handled by the caller checking source != dbgap.

    # If the UCUM unit is not in our map, we can't verify -- don't flag
    if ucum_clean not in _UCUM_TO_DBGAP:
        return True

    # UCUM is in our map but dbGaP unit doesn't match any equivalent
    return False


def _walk_slot_derivations(block: dict):
    """Yield (class_name, slot_name, slot_def, nearest_pht) for every slot at every depth."""
    for site in walk_slot_derivations(block):
        yield site.class_name, site.slot_name, site.slot_def, site.pht


def check_unit_conversion_mismatch(
    block: dict, block_idx: int, rel_path: str,
    detail_idx: DetailIndex,
) -> list[Finding]:
    """Check 3.14: unit_conversion source_unit vs dbGaP declared unit.

    When a slot has unit_conversion with source_unit, the declared
    source_unit should match what dbGaP says the variable's unit is.
    If dbGaP says the variable is already in the target unit, the
    conversion would corrupt the data (e.g., halving weights).
    """
    findings: list[Finding] = []

    for cls_name, slot_name, slot_def, parent_pht in _walk_slot_derivations(block):
        uc = slot_def.get("unit_conversion")
        if not isinstance(uc, dict):
            continue

        source_unit = uc.get("source_unit")
        target_unit = uc.get("target_unit")
        if not source_unit:
            continue

        # Find the PHV being converted
        phv = slot_def.get("populated_from")
        if not isinstance(phv, str) or not PHV_RE.fullmatch(phv):
            continue

        detail = detail_idx.records.get(phv)
        if not detail or not detail.unit:
            continue

        dbgap_unit = detail.unit

        # Check: does source_unit match what dbGaP declares?
        if not _units_compatible(source_unit, dbgap_unit):
            # Additional check: is dbGaP unit actually the TARGET unit?
            # This means source is already converted -- critical error.
            target_matches_dbgap = False
            if target_unit:
                target_clean = str(target_unit).strip().strip("'\"").lower()
                if target_clean == dbgap_unit.strip().lower():
                    target_matches_dbgap = True

            if target_matches_dbgap:
                severity = "CRITICAL"
                detail_msg = (
                    f"dbGaP declares unit='{dbgap_unit}' which matches "
                    f"target_unit='{target_unit}' -- source data is ALREADY "
                    f"in the target unit. This conversion will corrupt values"
                )
            else:
                severity = "ERROR"
                detail_msg = (
                    f"dbGaP declares unit='{dbgap_unit}' which does not "
                    f"match source_unit='{source_unit}'"
                )

            findings.append(Finding(
                file=rel_path,
                block=block_idx,
                check="3.14",
                severity=severity,
                message=(
                    f"{cls_name}.{slot_name}: {phv} ({detail.name}) "
                    f"has unit_conversion source_unit='{source_unit}' but "
                    f"{detail_msg}"
                ),
            ))

    return findings


# ---------------------------------------------------------------------------
# Check 3.13: Condition Null-Default Risk (Collection Interval)
# ---------------------------------------------------------------------------

# Matches "Collected in: P1 P2 P3" style values
_COLLECTED_IN_RE = re.compile(r"^Collected\s+in:\s*(.+)$", re.IGNORECASE)

# Sub-phase aliases: if a parent phase is in coll_interval, its sub-phases
# are considered covered.  COPDGene P3B is "Phase 3 Short-term 1-year
# follow-up" -- a sub-visit of P3 that dbGaP rolls into "Collected in: P3".
_PHASE_SUB_ALIASES: dict[str, str] = {
    "P3B": "P3",  # COPDGene Phase 3B -> Phase 3
}


def _expand_ci_phases(ci_phases: set[str]) -> set[str]:
    """Expand collection-interval phases to include known sub-phase aliases."""
    expanded = set(ci_phases)
    for child, parent in _PHASE_SUB_ALIASES.items():
        if parent in ci_phases:
            expanded.add(child)
    return expanded

# Detects case() in expressions
_CASE_RE = re.compile(r"\bcase\s*\(")

# Matches case result strings: , "RESULT") or , 'RESULT')
_CASE_RESULT_DQ = re.compile(r',\s*"([^"]+)"\s*\)')
_CASE_RESULT_SQ = re.compile(r",\s*'([^']+)'\s*\)")


def _parse_ci_phases(coll_interval: str | None) -> set[str] | None:
    """Parse structured coll_interval into phase tokens, or None."""
    if not coll_interval:
        return None
    m = _COLLECTED_IN_RE.match(coll_interval.strip())
    if not m:
        return None
    tokens = m.group(1).split()
    return set(tokens) if tokens else None


def _extract_case_phases(expr: str) -> set[str]:
    """Extract visit phase tokens from a case() expression's result strings.

    E.g., case((..., 'COPDGene P1'), (..., 'COPDGene P2')) -> {'P1', 'P2'}
    """
    labels = _CASE_RESULT_DQ.findall(expr) + _CASE_RESULT_SQ.findall(expr)
    phases: set[str] = set()
    for label in labels:
        parts = label.strip().split()
        if len(parts) >= 2:
            token = parts[-1]
            if token != "None":
                phases.add(token)
    return phases


def check_condition_null_default(
    block: dict, block_idx: int, rel_path: str,
    detail_idx: DetailIndex,
) -> list[Finding]:
    """Check 3.13: Condition null-default risk from collection interval mismatch.

    For Condition class blocks that use value_mappings on condition_status:
    if the associated_visit case expression routes to phases where the
    condition_status source PHV is NOT collected (per coll_interval), the
    pipeline will see null and may default to ABSENT -- producing false
    negatives that look like valid data.

    This is a CRITICAL severity finding because the output is actively
    misleading (plausible enum value from null input).
    """
    findings: list[Finding] = []
    class_derivs = block.get("class_derivations")
    if not isinstance(class_derivs, dict):
        return findings

    for cls_name, cls_def in class_derivs.items():
        if cls_name != "Condition" or not isinstance(cls_def, dict):
            continue

        slot_derivs = cls_def.get("slot_derivations")
        if not isinstance(slot_derivs, dict):
            continue

        # Must have a case()-based associated_visit
        visit_slot = slot_derivs.get("associated_visit", {})
        if not isinstance(visit_slot, dict):
            continue
        visit_expr = visit_slot.get("expr")
        if not visit_expr or not _CASE_RE.search(str(visit_expr)):
            continue

        # Extract the phases from the visit case expression
        case_phases = _extract_case_phases(str(visit_expr))
        if not case_phases:
            continue

        # Find the condition_status PHV
        status_slot = slot_derivs.get("condition_status", {})
        if not isinstance(status_slot, dict):
            continue

        # Needs value_mappings (the pattern where null -> ABSENT happens)
        if not status_slot.get("value_mappings"):
            continue

        pf = status_slot.get("populated_from")
        if not isinstance(pf, str) or not PHV_RE.fullmatch(pf):
            continue

        detail = detail_idx.records.get(pf)
        if not detail or not detail.coll_interval:
            continue

        ci_phases = _parse_ci_phases(detail.coll_interval)
        if ci_phases is None:
            continue

        # Expand ci_phases with known sub-phase aliases
        # (e.g., P3 covers P3B in COPDGene)
        ci_expanded = _expand_ci_phases(ci_phases)

        uncovered = case_phases - ci_expanded
        if not uncovered:
            continue

        uncovered_str = ", ".join(sorted(uncovered))
        covered_str = ", ".join(sorted(ci_phases))

        findings.append(Finding(
            file=rel_path,
            block=block_idx,
            check="3.13",
            severity="CRITICAL",
            message=(
                f"Condition.condition_status ({pf}, {detail.name}) "
                f"is only collected at [{covered_str}] but visit case "
                f"routes to [{uncovered_str}] -- null "
                f"condition_status may default to ABSENT, producing "
                f"false negatives"
            ),
        ))

    return findings


# ---------------------------------------------------------------------------
# Check 3.15: Phantom Code Detection
# ---------------------------------------------------------------------------


def check_phantom_codes(
    block: dict, block_idx: int, rel_path: str,
    detail_idx: DetailIndex,
    stats: dict | None = None,
) -> list[Finding]:
    """Check 3.15: ``value_mappings`` keys no row can match.

    Against the var_report's observed values:
      - a key that is observed: nothing (an observed code the dictionary omits is INFO, so the
        target can be checked against study documentation);
      - a key equal to an observed value except for case or whitespace: ERROR, it never matches
        (linkml-map compares exact strings) and those rows lose their value;
      - a slot none of whose keys matches any observed value: ERROR, the whole slot is dead --
        unless it is a severity slot whose only observed values mean "none";
      - a key neither observed nor declared (a defensive code no row carries): INFO. A declared
        code no row carries is not reported.
    Without var_report counts the declared codes are the reference, and a key outside them is a
    WARNING.
    """
    findings: list[Finding] = []
    for site, pf, vm in _vm_slots(block):
        cls_name, slot_name = site.class_name, site.slot_name
        detail = detail_idx.records.get(pf)
        declared = {str(k): str(v) for k, v in ((detail.codes or {}) if detail else {}).items()}
        observed = observed_values(stats, pf)
        keys = [str(k) for k in vm]
        where = f"value_mappings on {cls_name}.{slot_name} ({pf}{', ' + detail.name if detail else ''})"

        if observed is None:
            if not declared:
                continue
            for key in keys:
                if key not in declared and key not in declared.values():
                    findings.append(Finding(
                        rel_path, block_idx, "3.15", "WARNING",
                        f"{where} has key '{key}', which is not a declared code, and the "
                        f"var_report records no coded value for the variable (all null, or "
                        f"uncoded), so no row is known to carry it. Declared: {sorted(declared)}",
                    ))
            continue

        def _norm(x: str) -> str:
            return " ".join(x.split()).casefold()

        obs_norm = {_norm(v): v for v in observed}
        matched = [k for k in keys if k in observed]
        if not matched and observed:
            labels = [declared.get(v, v) for v in observed]
            if not (slot_name.endswith("_severity")
                    and all(_NO_SEVERITY_RE.match(lbl) for lbl in labels)):
                findings.append(Finding(
                    rel_path, block_idx, "3.15", "ERROR",
                    f"{where}: no key matches any observed value -- every row emits no value. "
                    f"Keys {sorted(keys)}; observed {sorted(observed)}",
                ))
                continue
        for key in keys:
            if key in observed:
                if declared and key not in declared and key not in declared.values():
                    findings.append(Finding(
                        rel_path, block_idx, "3.15", "INFO",
                        f"{where} key '{key}' is observed ({observed[key]:,} rows) but not in the "
                        f"data dictionary -- its meaning is undocumented, check the target",
                    ))
                continue
            twin = obs_norm.get(_norm(key))
            if twin is not None and twin not in keys:
                findings.append(Finding(
                    rel_path, block_idx, "3.15", "ERROR",
                    f"{where} key '{key}' never matches: the data holds '{twin}' "
                    f"({observed[twin]:,} rows), which differs only in case or spacing",
                ))
            elif twin is None and key not in declared and key not in declared.values():
                findings.append(Finding(
                    rel_path, block_idx, "3.15", "INFO",
                    f"{where} key '{key}' matches no observed value (dead key)",
                ))
    return findings


# ---------------------------------------------------------------------------
# Check 3.16: Quantity Missing Unit
# ---------------------------------------------------------------------------


#: observation_type CURIEs whose value is genuinely dimensionless, so a Quantity without a unit is
#: correct. Empty: every measured value on main has a unit. A dimensionless value can instead carry
#: the UCUM unit "1".
UNITLESS_OBSERVATION_TYPES: dict[str, str] = {}


def check_quantity_missing_unit(
    block: dict, block_idx: int, rel_path: str,
) -> list[Finding]:
    """Check 3.16: a measured value (Quantity value_decimal / value_integer) with no unit (ERROR).

    Walks every depth (a Quantity inside a MeasurementObservation inside a Set included). The
    value of a Quantity without a unit cannot be interpreted downstream, and a block that
    converts the value (``* 38.67``) without stating the unit is a silent scale error.
    """
    findings: list[Finding] = []

    def visit(cls_name: str, cls_def: dict, where: str, obs_type: str | None) -> None:
        slots = cls_def.get("slot_derivations")
        if not isinstance(slots, dict):
            return
        ot = slots.get("observation_type")
        if isinstance(ot, dict) and isinstance(ot.get("value"), str):
            obs_type = ot["value"]
        if cls_name == "Quantity":
            numeric = next((n for n in ("value_decimal", "value_integer") if n in slots), None)
            if numeric and "unit" not in slots and obs_type not in UNITLESS_OBSERVATION_TYPES:
                findings.append(Finding(
                    file=rel_path, block=block_idx, check="3.16", severity="ERROR",
                    message=(
                        f"Quantity{(' (in ' + where + ')') if where else ''} has {numeric} but "
                        f"no unit (observation_type {obs_type or 'none'}) -- the measured value "
                        f"cannot be interpreted. Add the unit, or '1' for a dimensionless value"
                    ),
                ))
        for slot_name, slot_def in slots.items():
            if isinstance(slot_def, dict):
                for ncls, ndef in iter_nested_class_derivs(slot_def):
                    if isinstance(ndef, dict):
                        visit(ncls, ndef, f"{where + '.' if where else ''}{cls_name}.{slot_name}",
                              obs_type)

    class_derivs = block.get("class_derivations")
    if isinstance(class_derivs, dict):
        for cls_name, cls_def in class_derivs.items():
            if isinstance(cls_def, dict):
                visit(cls_name, cls_def, "", None)
    return findings


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="HV-Lint Phase 3: Semantic validation (3.9, 3.10, 3.12-3.16)"
    )
    p.add_argument(
        "--cache-dir", required=True,
        help="Directory containing per-cohort *_detail.json.gz indexes"
    )
    p.add_argument(
        "--cohort", default="all",
        help="Cohort to validate or 'all' (default: all)"
    )
    p.add_argument(
        "--expect-study", default=None,
        help="OVERRIDE the release the cohort declares (phs000287 or phs000287.v7). The check "
             "always runs: without this flag the expectation comes from the cohort's "
             "_manifest-<cohort>.yaml, and a cache with no recorded provenance fails it.",
    )
    p.add_argument(
        "--fail-on", default="error",
        choices=["critical", "error", "high", "warning", "info"],
        help="Minimum severity for non-zero exit (default: error)"
    )
    p.add_argument(
        "--check", nargs="*", default=None,
        choices=["3.9", "3.10", "3.12", "3.13", "3.14", "3.15", "3.16"],
        help="Run only specific checks (default: all)"
    )
    return p.parse_args()


def main() -> int:
    args = parse_args()
    in_ci = os.environ.get("GITHUB_ACTIONS") == "true"
    cache_dir = Path(args.cache_dir)
    enabled_checks = set(args.check) if args.check else {"3.9", "3.10", "3.12", "3.13", "3.14", "3.15", "3.16"}

    if not cache_dir.is_dir():
        print(f"ERROR: Cache directory not found: {cache_dir}", file=sys.stderr)
        print("Run build_phv_detail_index.py first.", file=sys.stderr)
        return 1

    # Load detail indexes
    indexes: dict[str, DetailIndex] = {}
    stats_by_cohort: dict[str, dict | None] = {}
    pairs = _cohorts.cohorts_to_load(args.cohort, cache_dir, find_transform_dir())
    missing: list[tuple[str, str]] = []
    for cohort_name, cache_key in pairs:
        try:
            indexes[cohort_name] = load_detail_index(cache_dir, cache_key)
            stats_by_cohort[cohort_name] = _css.load_stats_index(cache_dir, cache_key)
            if stats_by_cohort[cohort_name] is None:
                print(f"ERROR: no {cache_key}_stats.json.gz for {cohort_name}: 3.9 / 3.15 "
                      f"compare against observed values and cannot run without it.",
                      file=sys.stderr)
                return 1
            count = len(indexes[cohort_name].records)
            coded = sum(1 for r in indexes[cohort_name].records.values() if r.codes)
            print(f"  Loaded {cohort_name}: {count:,} PHVs ({coded:,} coded) "
                  f"[{_cohorts.study_label(cache_dir, cache_key)}]")
            # The release being linted against is ALWAYS checked, never assumed. `--expect-study`
            # overrides; otherwise the cohort's own declaration in
            # hv_dataqc/cache_fetcher/manifests/_manifest-<cohort>.yaml is the expectation. A
            # cohort that declares nothing is a hard failure, because "lint against whichever
            # cache happens to be present" is how a superseded release goes unnoticed.
            expected = args.expect_study or _cohorts.declared_study(cohort_name, cache_dir=cache_dir)
            if not expected:
                print(
                    f"ERROR: cohort '{cohort_name}' declares no dbGaP release, so the cache "
                    f"cannot be checked. Add hv_dataqc/cache_fetcher/manifests/"
                    f"_manifest-<cohort>.yaml with current_version.study_id and data_version, "
                    f"or pass --expect-study phs######.v#.",
                    file=sys.stderr,
                )
                return 1
            source = "--expect-study" if args.expect_study else "declared release"
            mismatch = _cohorts.study_mismatch(cache_dir, cache_key, expected)
            if mismatch:
                print(f"ERROR: study version check ({source} {expected}): {mismatch}",
                      file=sys.stderr)
                return 1
        except FileNotFoundError:
            missing.append((cohort_name, cache_key))

    # A cache the run asked for and did not get is a HARD failure naming what it looked for.
    # Previously an unresolvable cohort produced an empty dict and the generic message "No dbGaP
    # indexes found. Run build_phv_index.py." -- which names the wrong remedy when the cache is
    # present but the cohort was simply not on the list, and cannot say WHICH cohort failed.
    if missing:
        for cohort_name, cache_key in missing:
            print(
                f"ERROR: no dbGaP index for cohort '{cohort_name}' -- looked for "
                f"'{cache_key}.json.gz' in {cache_dir}. Build it with build_phv_index.py "
                f"and build_phv_detail_index.py (--source-cache <dbgap staging dir>).",
                file=sys.stderr,
            )
        return 1

    # Discover YAML files
    base_dir = find_transform_dir()
    hv_root = base_dir.parent
    yaml_files = find_yaml_files(base_dir, args.cohort)
    if not yaml_files:
        print(f"No YAML files found under {base_dir}")
        return 0

    print(f"Found {len(yaml_files)} YAML files to validate")
    print(f"Enabled checks: {', '.join(sorted(enabled_checks))}")

    # Run checks
    all_findings: list[Finding] = []
    followup_idx: dict[str, object] = {}
    files_checked = 0
    blocks_checked = 0

    for file_path in yaml_files:
        rel_path = file_path.relative_to(hv_root).as_posix()

        cohort = detect_cohort(file_path)
        if cohort not in indexes:
            continue

        try:
            with file_path.open(encoding="utf-8") as f:
                data = yaml.safe_load(f)
        except (OSError, yaml.YAMLError):
            continue

        if data is None:
            continue

        blocks = data if isinstance(data, list) else [data]
        files_checked += 1
        detail_idx = indexes[cohort]
        stats = stats_by_cohort.get(cohort)
        if cohort not in followup_idx:
            followup_idx[cohort] = _css.DetailIndex.from_records(detail_idx.records)

        # Pre-compute file domain for 3.12
        file_domain = _filename_domain_keywords(file_path.name)

        for idx, block in enumerate(blocks):
            blocks_checked += 1
            if not isinstance(block, dict):
                continue

            if "3.9" in enabled_checks:
                all_findings.extend(
                    check_value_mappings_completeness(
                        block, idx, rel_path, detail_idx, stats, followup_idx[cohort]
                    )
                )
            if "3.10" in enabled_checks:
                all_findings.extend(
                    check_phv_type_compatibility(
                        block, idx, rel_path, detail_idx
                    )
                )
            if "3.12" in enabled_checks:
                all_findings.extend(
                    check_phv_domain_mismatch(
                        block, idx, rel_path, detail_idx, file_domain
                    )
                )
            if "3.13" in enabled_checks:
                all_findings.extend(
                    check_condition_null_default(
                        block, idx, rel_path, detail_idx
                    )
                )
            if "3.14" in enabled_checks:
                all_findings.extend(
                    check_unit_conversion_mismatch(
                        block, idx, rel_path, detail_idx
                    )
                )
            if "3.15" in enabled_checks:
                all_findings.extend(
                    check_phantom_codes(
                        block, idx, rel_path, detail_idx, stats
                    )
                )
            if "3.16" in enabled_checks:
                all_findings.extend(
                    check_quantity_missing_unit(
                        block, idx, rel_path,
                    )
                )

    # Report
    # Known issues, stale entries and the WARNING ratchet (hv-lint/_known_issues.py).
    all_findings.extend(_known_issues.finalize(
        all_findings, checks=enabled_checks, scanned_files=yaml_files, make_finding=Finding))

    fail_rank = SEVERITY_RANK[args.fail_on.upper()]

    counts: dict[str, int] = {}
    for f in all_findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1

    findings_by_file: dict[str, list[Finding]] = {}
    for f in all_findings:
        findings_by_file.setdefault(f.file, []).append(f)

    print(f"\n{'='*70}")
    print("HV-Lint Phase 3: Semantic Validation Results")
    print(f"{'='*70}")
    print(f"Files checked:  {files_checked}")
    print(f"Blocks checked: {blocks_checked}")

    parts = []
    for sev in ("CRITICAL", "ERROR", "HIGH", "WARNING", "INFO"):
        if counts.get(sev, 0) > 0:
            parts.append(f"{counts[sev]} {sev}")
    if parts:
        print(f"Findings:       {', '.join(parts)}")
    else:
        print("Findings:       None -- all semantic checks passed!")

    if findings_by_file:
        print(f"\n{'-'*70}")
        for fpath in sorted(findings_by_file):
            short = fpath.replace("priority_variables_transform/", "")
            print(f"\n{short}:")
            for f in sorted(findings_by_file[fpath], key=lambda x: (x.block, x.check)):
                print(f.terminal_line())
                if in_ci:
                    print(f.gh_annotation())

    blocking = [
        f for f in all_findings
        if SEVERITY_RANK.get(f.severity, 0) >= fail_rank
    ]
    if blocking:
        print(f"\nFAILED: {len(blocking)} findings at or above '{args.fail_on}'")
        return 1
    if all_findings:
        print(f"\nPASSED (with {len(all_findings)} advisory findings below fail threshold)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
