#!/usr/bin/env python3
"""HV-Lint Phase 3: dbGaP cross-reference validation for HV YAML files.

Validates that PHV and PHT accessions referenced in transformation YAML
files actually exist in the dbGaP variable index and have correct
table membership.

Requires a pre-built compressed index (generated by build_phv_index.py).

Usage:
    python hv-lint/phase-3/validate_dbgap_crossref.py --cache-dir hv-lint/dbgap-cache
    python hv-lint/phase-3/validate_dbgap_crossref.py --cache-dir hv-lint/dbgap-cache --cohort ARIC

Checks implemented:
    3.1  PHV/PHT accession format -- malformed accessions flagged
    3.2  PHT existence -- referenced PHTs must exist in dbGaP index
    3.3  PHV existence -- referenced PHVs must exist in dbGaP index
    3.4  Qualified reference -- a dotted ``{pht.phv}`` must name the table the PHV is in (ERROR)
    3.5  Cross-table reference without a join -- a BARE ``{phv}`` (or bare ``populated_from``)
         whose table is neither the block's class table, the ``populated_from`` of an enclosing
         nested derivation, nor a declared join (ERROR, every slot)

How linkml-map 0.5.3 resolves references (dm-bip's own schema step and map call): a dotted
``{pht.phv}`` and a nested derivation's ``populated_from`` table are reached through a join it
synthesizes on ``dbGaP_Subject_ID``, so they produce no finding. A bare reference to another
table's column makes no join: the value is None on every row (exit 0, one pre-flight log line),
or, for a ``populated_from`` whose column is in no loaded table, the entity run aborts.
"""

from __future__ import annotations

import argparse
import gzip
import json
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

# Path resolution -- works in both control center and HV repo
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from _paths import find_transform_dir  # noqa: E402
import _known_issues  # noqa: E402
import _cohorts  # noqa: E402
from _derivations import iter_nested_class_derivs, walk_slot_derivations  # noqa: E402

import yaml




# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

SEVERITY_RANK = {"CRITICAL": 5, "ERROR": 4, "HIGH": 3, "WARNING": 2, "INFO": 1}

# A reference inside an expression: ``{phv}`` or the qualified ``{pht.phv}``.
REF_RE = re.compile(r"\{(?:(pht\d{6})\.)?(phv\d{8})\}")
# A ``populated_from`` may also be qualified: ``pht003099.phv00177932``.
QUALIFIED_PF_RE = re.compile(r"^(?:(pht\d{6})\.)?(phv\d{8})$")

# ---------------------------------------------------------------------------
# Accession format regexes
# ---------------------------------------------------------------------------

# Strict format: the canonical dbGaP accession pattern
PHV_STRICT_RE = re.compile(r"phv\d{8}(?!\d)")
PHT_STRICT_RE = re.compile(r"pht\d{6}(?!\d)")

# Loose format: catches anything that looks like a PHV/PHT but may have
# wrong digit count -- used by check 3.1 to detect malformed accessions
PHV_LOOSE_RE = re.compile(r"phv\d+")
PHT_LOOSE_RE = re.compile(r"pht\d+")

# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class Finding:
    file: str
    block: int
    check: str       # e.g., "3.1"
    severity: str    # CRITICAL, ERROR, WARNING, INFO
    message: str

    @staticmethod
    def _esc_prop(text: str) -> str:
        """Escape a workflow-command *property* value (file=, line=, ...)."""
        return (text.replace("%", "%25").replace("\r", "%0D")
                .replace("\n", "%0A").replace(":", "%3A").replace(",", "%2C"))

    @staticmethod
    def _esc_msg(text: str) -> str:
        """Escape a workflow-command *message* (colons/commas stay readable)."""
        return text.replace("%", "%25").replace("\r", "%0D").replace("\n", "%0A")

    def gh_annotation(self) -> str:
        level = {
            "CRITICAL": "error", "ERROR": "error",
            "WARNING": "warning", "HIGH": "warning", "INFO": "notice",
        }.get(self.severity, "notice")
        return f"::{level} file={self._esc_prop(self.file)}::HV-Lint [{self.check}] {self._esc_msg(self.message)} (block {self.block})"

    def terminal_line(self) -> str:
        sev = self.severity[:5].ljust(5)
        return f"  {sev}  block {self.block:>3}  [{self.check}] {self.message}"


@dataclass
class DbGaPIndex:
    """Pre-built dbGaP index for a single cohort."""
    phv_to_pht: dict[str, str] = field(default_factory=dict)  # phv -> pht
    valid_phts: set[str] = field(default_factory=set)

# ---------------------------------------------------------------------------
# Index loading
# ---------------------------------------------------------------------------

def load_dbgap_index(cache_dir: Path, cache_key: str) -> DbGaPIndex:
    """Load compressed phv->pht index for a cohort."""
    gz_path = cache_dir / f"{cache_key}.json.gz"
    json_path = cache_dir / f"{cache_key}.json"

    if gz_path.exists():
        with gzip.open(gz_path, "rt", encoding="utf-8") as f:
            mapping = json.load(f)
    elif json_path.exists():
        with json_path.open(encoding="utf-8") as f:
            mapping = json.load(f)
    else:
        raise FileNotFoundError(
            f"No dbGaP index for '{cache_key}': "
            f"expected {gz_path} or {json_path}"
        )

    idx = DbGaPIndex()
    idx.phv_to_pht = mapping
    idx.valid_phts = set(mapping.values())
    return idx

# ---------------------------------------------------------------------------
# File discovery
# ---------------------------------------------------------------------------

def find_yaml_files(base_dir: Path, cohort: str) -> list[Path]:
    files = sorted(
        f for f in base_dir.rglob("*.yaml")
        if any("-ingest" in part for part in f.parts)
        and not f.name.endswith(".swp")
    )
    if cohort.lower() != "all":
        pattern = f"{cohort}-ingest".lower()
        files = [f for f in files if any(part.lower() == pattern for part in f.parts)]
    return files


def detect_cohort(file_path: Path) -> str:
    for part in file_path.parts:
        if part.endswith("-ingest"):
            return part.replace("-ingest", "")
    return "UNKNOWN"

# ---------------------------------------------------------------------------
# Reference extraction
# ---------------------------------------------------------------------------

def _slot_references(block: dict):
    """Yield ``(site, phv, qualifier_pht_or_None, context)`` for every PHV a slot reads."""
    for site in walk_slot_derivations(block):
        sd = site.slot_def
        context = f"{site.slot_name} on {site.class_name}"
        seen: set[tuple[str, str | None]] = set()

        def _emit(phv, qual, ctx):
            if (phv, qual) not in seen:
                seen.add((phv, qual))
                return [(site, phv, qual, ctx)]
            return []

        out = []
        pf = sd.get("populated_from")
        if isinstance(pf, str):
            m = QUALIFIED_PF_RE.match(pf.strip())
            if m:
                out += _emit(m.group(2), m.group(1), context)
        expr = sd.get("expr")
        if isinstance(expr, str):
            for m in REF_RE.finditer(expr):
                out += _emit(m.group(2), m.group(1), f"expr in {context}")
        for key_name in ("value_mappings", "expression_to_value_mappings"):
            mapping = sd.get(key_name)
            if isinstance(mapping, dict):
                for k in mapping:
                    for m in PHV_STRICT_RE.finditer(str(k)):
                        out += _emit(m.group(), None, f"{key_name} key in {context}")
        yield from out


# ---------------------------------------------------------------------------
# Check 3.1: Accession format validation
# ---------------------------------------------------------------------------

def _collect_accession_strings(block: dict) -> list[tuple[str, str]]:
    """Collect all string values that look like PHV/PHT accessions.

    Returns list of (accession_string, context_description).
    Uses loose regex to catch malformed accessions that the strict
    regex would silently skip.
    """
    results: list[tuple[str, str]] = []
    class_derivs = block.get("class_derivations")
    if not isinstance(class_derivs, dict):
        return results

    for class_name, class_def in class_derivs.items():
        if not isinstance(class_def, dict):
            continue

        # Class populated_from (PHT)
        pf = class_def.get("populated_from")
        if isinstance(pf, str):
            for m in PHT_LOOSE_RE.finditer(pf):
                results.append((m.group(), f"populated_from on {class_name}"))
            for m in PHV_LOOSE_RE.finditer(pf):
                results.append((m.group(), f"populated_from on {class_name}"))

        # Joins -- linkml-map defines `joins` as Dict[str, AliasedClass]
        # where the key is the alias of the joined class (the PHT in this
        # repo's convention). Also accept the alternate list form where
        # the PHT is carried in each item's `populated_from`.
        raw_joins = class_def.get("joins")
        if isinstance(raw_joins, dict):
            for k, v in raw_joins.items():
                if isinstance(k, str):
                    for m in PHT_LOOSE_RE.finditer(k):
                        results.append((m.group(), f"joins on {class_name}"))
                if isinstance(v, dict):
                    jpf = v.get("populated_from")
                    if isinstance(jpf, str):
                        for m in PHT_LOOSE_RE.finditer(jpf):
                            results.append((m.group(), f"joins on {class_name}"))
                    # Join keys carry PHV accessions (source_key / lookup_key).
                    for key_field in ("source_key", "lookup_key"):
                        kv = v.get(key_field)
                        if isinstance(kv, str):
                            for m in PHV_LOOSE_RE.finditer(kv):
                                results.append(
                                    (m.group(), f"joins {key_field} on {class_name}")
                                )
        elif isinstance(raw_joins, list):
            for j in raw_joins:
                if isinstance(j, dict):
                    jpf = j.get("populated_from")
                    if isinstance(jpf, str):
                        for m in PHT_LOOSE_RE.finditer(jpf):
                            results.append((m.group(), f"joins on {class_name}"))

        # Walk slot_derivations
        slot_derivs = class_def.get("slot_derivations")
        if isinstance(slot_derivs, dict):
            results.extend(_collect_slot_accessions(slot_derivs, class_name))

    return results


def _collect_slot_accessions(
    slot_derivs: dict, class_name: str
) -> list[tuple[str, str]]:
    """Collect accession-like strings from slot_derivations."""
    results: list[tuple[str, str]] = []
    for slot_name, slot_def in slot_derivs.items():
        if not isinstance(slot_def, dict):
            continue

        pf = slot_def.get("populated_from")
        if isinstance(pf, str):
            for m in PHV_LOOSE_RE.finditer(pf):
                results.append((m.group(), f"{slot_name} on {class_name}"))

        expr = slot_def.get("expr")
        if isinstance(expr, str):
            for m in PHV_LOOSE_RE.finditer(expr):
                results.append((m.group(), f"expr in {slot_name} on {class_name}"))

        for key_name in ("value_mappings", "expression_to_value_mappings"):
            mapping = slot_def.get(key_name)
            if isinstance(mapping, dict):
                for k in mapping:
                    if isinstance(k, str):
                        for m in PHV_LOOSE_RE.finditer(k):
                            results.append((m.group(), f"{key_name} in {slot_name} on {class_name}"))

        # Recurse into nested class derivations (list-based or legacy
        # object_derivations)
        for nested_cls, nested_def in iter_nested_class_derivs(slot_def):
            if isinstance(nested_def, dict):
                npf = nested_def.get("populated_from")
                if isinstance(npf, str):
                    for m in PHT_LOOSE_RE.finditer(npf):
                        results.append((m.group(), f"nested populated_from on {nested_cls}"))
                nested_slots = nested_def.get("slot_derivations")
                if isinstance(nested_slots, dict):
                    results.extend(_collect_slot_accessions(nested_slots, nested_cls))
    return results


def check_accession_format(
    block: dict, block_idx: int, rel_path: str
) -> list[Finding]:
    """Check 3.1: Flag accession strings that don't match canonical format."""
    findings: list[Finding] = []
    seen: set[tuple[str, str]] = set()

    for accession, context in _collect_accession_strings(block):
        key = (accession, context)
        if key in seen:
            continue
        seen.add(key)

        if accession.startswith("phv"):
            if not PHV_STRICT_RE.fullmatch(accession):
                findings.append(Finding(
                    rel_path, block_idx, "3.1", "ERROR",
                    f"Malformed PHV '{accession}' ({context}) -- "
                    f"expected phv + exactly 8 digits"
                ))
        elif accession.startswith("pht"):
            if not PHT_STRICT_RE.fullmatch(accession):
                findings.append(Finding(
                    rel_path, block_idx, "3.1", "ERROR",
                    f"Malformed PHT '{accession}' ({context}) -- "
                    f"expected pht + exactly 6 digits"
                ))

    return findings


# ---------------------------------------------------------------------------
# Checks 3.2-3.5
# ---------------------------------------------------------------------------

def check_block(
    block: dict, block_idx: int, rel_path: str,
    dbgap: DbGaPIndex
) -> list[Finding]:
    """Run checks 3.2-3.5 on a single block."""
    findings: list[Finding] = []
    class_derivs = block.get("class_derivations")
    if not isinstance(class_derivs, dict):
        return findings

    for class_name, class_def in class_derivs.items():
        if not isinstance(class_def, dict):
            continue

        raw_pht = class_def.get("populated_from", "")
        class_pht = raw_pht if isinstance(raw_pht, str) and PHT_STRICT_RE.fullmatch(raw_pht) else ""
        raw_joins = class_def.get("joins")
        if raw_joins is not None and not isinstance(raw_joins, (dict, list)):
            findings.append(Finding(
                rel_path, block_idx, "3.0", "ERROR",
                f"{class_name} joins is "
                f"{type(raw_joins).__name__}, expected dict or list"
            ))
        slot_derivs = class_def.get("slot_derivations")
        if not isinstance(slot_derivs, dict):
            if slot_derivs is not None:
                findings.append(Finding(
                    rel_path, block_idx, "3.0", "ERROR",
                    f"{class_name} slot_derivations is "
                    f"{type(slot_derivs).__name__}, expected mapping"
                ))
            slot_derivs = {}

        # Collect join PHTs for cross-table detection. linkml-map's
        # canonical form is Dict[str, AliasedClass] keyed by the joined
        # class alias (the PHT in this repo). The list form carries the
        # PHT in each item's populated_from.
        join_phts: set[str] = set()
        join_phvs: list[tuple[str, str]] = []
        if isinstance(raw_joins, dict):
            for k, v in raw_joins.items():
                if isinstance(k, str) and PHT_STRICT_RE.fullmatch(k):
                    join_phts.add(k)
                if isinstance(v, dict):
                    jpht = v.get("populated_from", "")
                    if isinstance(jpht, str) and PHT_STRICT_RE.fullmatch(jpht):
                        join_phts.add(jpht)
                    for key_field in ("source_key", "lookup_key"):
                        kv = v.get(key_field)
                        if isinstance(kv, str):
                            for m in PHV_STRICT_RE.finditer(kv):
                                join_phvs.append(
                                    (m.group(), f"{key_field} in joins on {class_name}")
                                )
        elif isinstance(raw_joins, list):
            for j in raw_joins:
                if isinstance(j, dict):
                    jpht = j.get("populated_from", "")
                    if isinstance(jpht, str) and PHT_STRICT_RE.fullmatch(jpht):
                        join_phts.add(jpht)

        # -- Check 3.2: PHT existence --
        if class_pht and class_pht not in dbgap.valid_phts:
            findings.append(Finding(
                rel_path, block_idx, "3.2", "ERROR",
                f"PHT '{class_pht}' on {class_name} not found in "
                f"dbGaP variable index"
            ))

        # -- Check 3.3: PHV existence for join keys (source_key / lookup_key) --
        for phv, context in join_phvs:
            if phv not in dbgap.phv_to_pht:
                findings.append(Finding(
                    rel_path, block_idx, "3.3", "ERROR",
                    f"PHV '{phv}' ({context}) not found in dbGaP index"
                ))

        # -- Checks 3.3 / 3.4 / 3.5 over every slot at every depth --
        block_view = {"class_derivations": {class_name: class_def}}
        for site, phv, qualifier, context in _slot_references(block_view):
            if phv not in dbgap.phv_to_pht:
                findings.append(Finding(
                    rel_path, block_idx, "3.3", "ERROR",
                    f"PHV '{phv}' ({context}) not found in dbGaP index"
                ))
                continue
            actual_pht = dbgap.phv_to_pht[phv]
            if qualifier:
                if qualifier != actual_pht:
                    findings.append(Finding(
                        rel_path, block_idx, "3.4", "ERROR",
                        f"'{{{qualifier}.{phv}}}' ({context}) names {qualifier}, but {phv} is in "
                        f"{actual_pht} -- the synthesized join reads the wrong table"
                    ))
                continue
            if not class_pht:
                continue
            reachable = set(site.tables) | join_phts
            if actual_pht in reachable:
                continue
            findings.append(Finding(
                rel_path, block_idx, "3.5", "ERROR",
                f"PHV '{phv}' ({context}) belongs to {actual_pht}, which is not the class table "
                f"{class_pht}"
                + (f", an enclosing nested table ({', '.join(site.tables[1:])})"
                   if len(site.tables) > 1 else "")
                + " or a declared join -- a bare cross-table reference resolves to None in "
                f"linkml-map (write {{{actual_pht}.{phv}}} or use the block's own table's variable)"
            ))

    return findings


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="HV-Lint Phase 3: dbGaP cross-reference validation"
    )
    p.add_argument(
        "--cache-dir",
        required=True,
        help="Directory containing per-cohort .json.gz indexes"
    )
    p.add_argument(
        "--cohort", default="all",
        help="Cohort to validate (e.g., ARIC, CHS) or 'all' (default: all)"
    )
    p.add_argument(
        "--expect-study", default=None,
        help="OVERRIDE the release the cohort declares (phs000287 or phs000287.v7). The check "
             "always runs: without this flag the expectation comes from the cohort's "
             "_manifest-<cohort>.yaml, and a cache with no recorded provenance fails it.",
    )
    p.add_argument(
        "--fail-on", default="error",
        choices=["critical", "error", "high", "warning", "info"],
        help="Minimum severity to cause non-zero exit (default: error)"
    )
    p.add_argument(
        "--summary-file", default=None,
        help="Write a Markdown summary table to this file (for GITHUB_STEP_SUMMARY)"
    )
    p.add_argument(
        "--summary-limit", type=int, default=50,
        help="Max findings to include in the Markdown summary (default: 50)"
    )
    args = p.parse_args()
    _cohorts.reject_expect_study_for_all(p, args)
    return args


def main() -> int:
    args = parse_args()
    # The file scan matches `<cohort>-ingest`, so an alias (`hchs_sol`, `HCHS-SOL`) must name
    # the DIRECTORY here, as it already names the cache in `cohorts_to_load`; otherwise the
    # release check passes and the scan finds no file.
    args.cohort = _cohorts.canonical_cohort(args.cohort, find_transform_dir())
    in_ci = os.environ.get("GITHUB_ACTIONS") == "true"
    cache_dir = Path(args.cache_dir)

    if not cache_dir.is_dir():
        print(f"ERROR: Cache directory not found: {cache_dir}", file=sys.stderr)
        print("Run build_phv_index.py first to generate the indexes.", file=sys.stderr)
        return 1

    # Load indexes (only the needed cohort when filtering)
    indexes: dict[str, DbGaPIndex] = {}
    pairs = _cohorts.cohorts_to_load(args.cohort, cache_dir, find_transform_dir())
    missing: list[tuple[str, str]] = []
    for cohort_name, cache_key in pairs:
        try:
            indexes[cohort_name] = load_dbgap_index(cache_dir, cache_key)
            count = len(indexes[cohort_name].phv_to_pht)
            phts = len(indexes[cohort_name].valid_phts)
            print(f"  Loaded {cohort_name}: {count:,} PHVs across {phts} PHTs "
                  f"[{_cohorts.study_label(cache_dir, cache_key)}]")
            # The release being linted against is ALWAYS checked, never assumed. `--expect-study`
            # overrides; otherwise the cohort's own declaration in
            # hv_dataqc/cache_fetcher/manifests/_manifest-<cohort>.yaml is the expectation. A
            # cohort that declares nothing is a hard failure, because "lint against whichever
            # cache happens to be present" is how a superseded release goes unnoticed.
            expected = args.expect_study or _cohorts.declared_study(cohort_name, cache_dir=cache_dir)
            if not expected:
                print(
                    f"ERROR: cohort '{cohort_name}' declares no dbGaP release, so the cache "
                    f"cannot be checked. Add hv_dataqc/cache_fetcher/manifests/"
                    f"_manifest-<cohort>.yaml with current_version.study_id and data_version. "
                    f"(--expect-study phs######.v# overrides it for a one-off Phase 3 run on "
                    f"one named --cohort; Phase 5 has no override and still fails.)",
                    file=sys.stderr,
                )
                return 1
            source = "--expect-study" if args.expect_study else "declared release"
            mismatch = _cohorts.study_mismatch(cache_dir, cache_key, expected)
            if mismatch:
                print(f"ERROR: study version check ({source} {expected}): {mismatch}",
                      file=sys.stderr)
                return 1
        except FileNotFoundError:
            missing.append((cohort_name, cache_key))

    # A cache the run asked for and did not get is a HARD failure naming what it looked for.
    # Previously an unresolvable cohort produced an empty dict and the generic message "No dbGaP
    # indexes found. Run build_phv_index.py." -- which names the wrong remedy when the cache is
    # present but the cohort was simply not on the list, and cannot say WHICH cohort failed.
    if missing:
        for cohort_name, cache_key in missing:
            print(
                f"ERROR: no dbGaP index for cohort '{cohort_name}' -- looked for "
                f"'{cache_key}.json.gz' in {cache_dir}. Build it with build_phv_index.py "
                f"and build_phv_detail_index.py (--source-cache <dbgap staging dir>).",
                file=sys.stderr,
            )
        return 1

    # Discover YAML files
    base_dir = find_transform_dir()
    hv_root = base_dir.parent
    yaml_files = find_yaml_files(base_dir, args.cohort)
    if not yaml_files:
        print(f"No YAML files found under {base_dir}")
        return 1
    print(f"Found {len(yaml_files)} YAML files to validate")

    # Run checks
    all_findings: list[Finding] = []
    files_checked = 0
    blocks_checked = 0
    skipped_no_index: list[str] = []

    for file_path in yaml_files:
        rel_path = file_path.relative_to(hv_root).as_posix()

        cohort = detect_cohort(file_path)
        if cohort not in indexes:
            skipped_no_index.append(rel_path)
            continue

        try:
            with file_path.open(encoding="utf-8") as f:
                data = yaml.safe_load(f)
        except (OSError, UnicodeDecodeError, yaml.YAMLError) as exc:
            all_findings.append(Finding(
                check="3.0", severity="ERROR",
                file=rel_path, block=0,
                message=f"Cannot parse YAML: {exc}",
            ))
            continue

        if data is None:
            continue

        blocks = data if isinstance(data, list) else [data]
        files_checked += 1
        dbgap = indexes[cohort]

        for idx, block in enumerate(blocks):
            blocks_checked += 1
            if not isinstance(block, dict):
                continue
            # Check 3.1: accession format
            all_findings.extend(check_accession_format(block, idx, rel_path))
            # Checks 3.2-3.5: existence and membership
            all_findings.extend(check_block(block, idx, rel_path, dbgap))

    # -----------------------------------------------------------------------
    # Report
    # -----------------------------------------------------------------------
    # Surface missing-index skips as ERROR findings before building report
    if skipped_no_index:
        for skipped_file in skipped_no_index:
            all_findings.append(Finding(
                check="3.0", severity="ERROR",
                file=skipped_file, block=0,
                message="No dbGaP index available for cohort -- file not validated",
            ))

    # Known issues, stale entries and the WARNING ratchet (hv-lint/_known_issues.py).
    all_findings.extend(_known_issues.finalize(
        all_findings, checks={"3.0", "3.1", "3.2", "3.3", "3.4", "3.5"}, scanned_files=yaml_files, make_finding=Finding))

    fail_rank = SEVERITY_RANK[args.fail_on.upper()]

    counts: dict[str, int] = {}
    for f in all_findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1

    findings_by_file: dict[str, list[Finding]] = {}
    for f in all_findings:
        findings_by_file.setdefault(f.file, []).append(f)

    print(f"\n{'='*70}")
    print("HV-Lint Phase 3 Results")
    print(f"{'='*70}")
    print(f"Files checked:  {files_checked}")
    print(f"Blocks checked: {blocks_checked}")
    if skipped_no_index:
        print(f"Files skipped (no index): {len(skipped_no_index)}")

    parts = []
    for sev in ("CRITICAL", "ERROR", "HIGH", "WARNING", "INFO"):
        if counts.get(sev, 0) > 0:
            parts.append(f"{counts[sev]} {sev}")
    if parts:
        print(f"Findings:       {', '.join(parts)}")
    else:
        print("Findings:       None - all checks passed!")

    if findings_by_file:
        print(f"\n{'-'*70}")
        for fpath in sorted(findings_by_file):
            short = fpath.replace("priority_variables_transform/", "")
            print(f"\n{short}:")
            for f in sorted(findings_by_file[fpath], key=lambda x: (x.block, x.check)):
                print(f.terminal_line())
                if in_ci:
                    print(f.gh_annotation())

    # Write Markdown summary
    if args.summary_file:
        _write_summary(args.summary_file, "Phase 3", files_checked, blocks_checked,
                       counts, all_findings, args.summary_limit)

    blocking = [
        f for f in all_findings
        if SEVERITY_RANK.get(f.severity, 0) >= fail_rank
    ]
    if blocking:
        print(f"\n{'='*70}")
        print(f"FAILED: {len(blocking)} findings at or above '{args.fail_on}' severity")
        return 1
    else:
        if all_findings:
            print(f"\n{'='*70}")
            print(f"PASSED (with {len(all_findings)} advisory findings below fail threshold)")
        return 0


def _write_summary(path: str, phase: str, files: int, blocks: int,
                   counts: dict[str, int], findings: list[Finding],
                   limit: int) -> None:
    """Write a Markdown summary table for GITHUB_STEP_SUMMARY."""
    lines: list[str] = []
    lines.append(f"## HV-Lint {phase} Results\n")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Files checked | {files} |")
    lines.append(f"| Blocks checked | {blocks} |")
    for sev in ("CRITICAL", "ERROR", "HIGH", "WARNING", "INFO"):
        if counts.get(sev, 0) > 0:
            lines.append(f"| {sev} | {counts[sev]} |")
    lines.append("")
    if findings:
        sorted_findings = sorted(
            findings,
            key=lambda f: (-SEVERITY_RANK.get(f.severity, 0), f.file, f.block, f.check)
        )
        shown = sorted_findings[:limit]
        lines.append(f"### Findings (showing {len(shown)} of {len(findings)})\n")
        lines.append("| Severity | File | Block | Check | Message |")
        lines.append("|----------|------|-------|-------|---------|")
        for f in shown:
            short = f.file.replace("priority_variables_transform/", "")
            msg = f.message.replace("\r", " ").replace("\n", " ").replace("|", "\\|")
            lines.append(f"| {f.severity} | {short} | {f.block} | {f.check} | {msg} |")
        if len(findings) > limit:
            lines.append(
                f"\n> **{len(findings) - limit} additional findings omitted.** "
                f"Re-run with a higher `summary_limit` or check the raw log."
            )
    else:
        lines.append("All checks passed!\n")
    Path(path).write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    sys.exit(main())
