#!/usr/bin/env python3
"""HV-Lint Phase 3: Semantic validation using extended PHV detail index.

Validates that YAML transformation files are semantically consistent
with the dbGaP FTP data dictionaries. Requires the extended detail
index generated by build_phv_detail_index.py.

Checks:
    3.9   value_mappings completeness -- source codes in dbGaP but absent
          from value_mappings are flagged (silent data loss)
    3.10  PHV type vs slot role -- data type of source variable must be
          compatible with the target slot's expected role
    3.12  PHV description vs concept domain -- variable description keywords
          should not conflict with the file's clinical domain
    3.13  Condition null-default risk -- Condition blocks whose visit case
          routes to phases where condition_status PHV is not collected
          (null -> false ABSENT)
    3.14  unit_conversion source_unit mismatch -- unit_conversion source_unit
          must match the dbGaP-declared unit for the source PHV
    3.15  Phantom code detection -- value_mappings keys that don't exist in
          dbGaP coded values (typo, cross-cohort copy-paste, version drift)
    3.16  Quantity missing unit -- Quantity blocks with value_decimal or
          value_integer but no sibling unit slot

Usage:
    python hv-lint/phase-3/validate_semantic.py --cache-dir hv-lint/dbgap-cache
    python hv-lint/phase-3/validate_semantic.py --cache-dir hv-lint/dbgap-cache --cohort HCHS
"""

from __future__ import annotations

import argparse
import gzip
import json
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from _paths import find_transform_dir  # noqa: E402

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

COHORT_TO_CACHE_KEY: dict[str, str] = {
    "ARIC": "aric",
    "CARDIA": "cardia",
    "CHS": "chs",
    "COPDGene": "copdgene",
    "FHS": "fhs",
    "HCHS": "hchs_sol",
    "JHS": "jhs",
    "MESA": "mesa",
    "SPIROMICS": "spiromics",
    "WHI": "whi",
    "LTRC": "ltrc",
}

SEVERITY_RANK = {"CRITICAL": 5, "ERROR": 4, "HIGH": 3, "WARNING": 2, "INFO": 1}

PHV_RE = re.compile(r"phv\d{8}")

# Rule 3.9: Known skip-label patterns for coded values that are
# legitimately omitted from value_mappings.
SKIP_LABEL_RE = re.compile(
    r"unknown|refuse|don.t know|do not know|missing|N/?A|not applicable|"
    r"not recorded|no response|not assessed|blank",
    re.IGNORECASE,
)

# Rule 3.9: High-impact slots where missing coded values are virtually
# always bugs (real data silently lost), not intentional omissions.
# Missing codes in these slots are elevated from WARNING to ERROR.
# NOTE: ethnicity excluded -- frequently shares a PHV with race, so
# race-category codes would be false-positive ERRORs on ethnicity.
HIGH_IMPACT_SLOTS = {
    "race", "annotated_sex", "sex",
    "condition_status", "value_enum",
}

# Rule 3.10: Slot role -> expected dbGaP type mapping.
# Slots whose semantic role implies a specific data type.
ENUM_SLOTS = {
    "condition_status", "annotated_sex", "race", "ethnicity",
    "observation_type", "vital_status",
}
NUMERIC_SLOTS = {
    "value_decimal", "value_integer",
}

# Rule 3.12: Domain conflict pairs.
# If a file's domain keywords contain terms from column A,
# a PHV description containing terms from column B is flagged.
DOMAIN_CONFLICTS: list[tuple[set[str], set[str]]] = [
    ({"coronary", "heart", "cardiac", "myocardial"},
     {"carotid", "neck", "cerebral", "cerebrovascular"}),
    ({"carotid", "neck", "cerebral", "cerebrovascular"},
     {"coronary", "heart", "cardiac", "myocardial"}),
    ({"systolic"}, {"diastolic"}),
    ({"diastolic"}, {"systolic"}),
    ({"urine", "urinary"}, {"serum", "plasma", "blood"}),
    ({"serum", "plasma"}, {"urine", "urinary"}),
    ({"arm", "brachial"}, {"leg", "ankle", "pedal"}),
    ({"leg", "ankle"}, {"arm", "brachial"}),
    ({"fasting"}, {"postprandial", "random", "non-fasting"}),
    ({"lymphocyte"}, {"leukocyte", "white blood", "wbc", "neutrophil", "monocyte"}),
    ({"leukocyte", "white blood", "wbc"}, {"lymphocyte", "platelet", "red blood", "rbc"}),
    ({"platelet"}, {"white blood", "wbc", "leukocyte", "red blood", "rbc"}),
    ({"hemoglobin", "hgb"}, {"hematocrit", "platelet"}),
    ({"glucose"}, {"insulin", "creatinine", "cholesterol"}),
    ({"creatinine"}, {"glucose", "cholesterol", "triglyceride"}),
    ({"cholesterol", "ldl"}, {"triglyceride", "glucose", "creatinine"}),
    ({"triglyceride"}, {"cholesterol", "ldl", "hdl", "glucose"}),
    ({"height"}, {"weight", "bmi"}),
    ({"weight"}, {"height"}),
]

# ---------------------------------------------------------------------------
# Data Structures
# ---------------------------------------------------------------------------


@dataclass
class PhvDetail:
    """Per-variable metadata from the extended FTP index."""
    name: str
    pht: str
    type: str
    unit: str | None
    description: str
    codes: dict[str, str] | None
    coll_interval: str | None = None


@dataclass
class DetailIndex:
    """Extended PHV detail index for a single cohort."""
    records: dict[str, PhvDetail] = field(default_factory=dict)


@dataclass
class Finding:
    file: str
    block: int
    check: str
    severity: str
    message: str

    def terminal_line(self) -> str:
        sev = self.severity[:5].ljust(5)
        return f"  {sev}  block {self.block:>3}  [{self.check}] {self.message}"

    def gh_annotation(self) -> str:
        level = {
            "CRITICAL": "error", "ERROR": "error", "HIGH": "warning",
            "WARNING": "warning", "INFO": "notice",
        }.get(self.severity, "notice")
        file_esc = (self.file.replace("%", "%25").replace("\r", "%0D")
                    .replace("\n", "%0A").replace(":", "%3A").replace(",", "%2C"))
        msg_esc = self.message.replace("%", "%25").replace("\r", "%0D").replace("\n", "%0A")
        return f"::{level} file={file_esc}::HV-Lint [{self.check}] {msg_esc} (block {self.block})"


# ---------------------------------------------------------------------------
# Index Loading
# ---------------------------------------------------------------------------


def load_detail_index(cache_dir: Path, cache_key: str) -> DetailIndex:
    """Load the extended detail index for a cohort."""
    gz_path = cache_dir / f"{cache_key}_detail.json.gz"
    json_path = cache_dir / f"{cache_key}_detail.json"

    if gz_path.exists():
        with gzip.open(gz_path, "rt", encoding="utf-8") as f:
            raw = json.load(f)
    elif json_path.exists():
        with json_path.open(encoding="utf-8") as f:
            raw = json.load(f)
    else:
        raise FileNotFoundError(
            f"No detail index for '{cache_key}': expected {gz_path} or {json_path}"
        )

    idx = DetailIndex()
    for phv, rec in raw.items():
        idx.records[phv] = PhvDetail(
            name=rec.get("name", ""),
            pht=rec.get("pht", ""),
            type=rec.get("type", ""),
            unit=rec.get("unit"),
            description=rec.get("description", ""),
            codes=rec.get("codes"),
            coll_interval=rec.get("coll_interval"),
        )
    return idx


# ---------------------------------------------------------------------------
# File Discovery
# ---------------------------------------------------------------------------


def find_yaml_files(base_dir: Path, cohort: str) -> list[Path]:
    files = sorted(
        f for f in base_dir.rglob("*.yaml")
        if any("-ingest" in part for part in f.parts)
        and not f.name.endswith(".swp")
    )
    if cohort.lower() != "all":
        pattern = f"{cohort}-ingest".lower()
        files = [f for f in files if any(part.lower() == pattern for part in f.parts)]
    return files
    for part in file_path.parts:
        if part.endswith("-ingest"):
            return part.replace("-ingest", "")
    return "UNKNOWN"


# ---------------------------------------------------------------------------
# Utility: Extract domain keywords from filename
# ---------------------------------------------------------------------------

def _filename_domain_keywords(filename: str) -> set[str]:
    """Extract domain keywords from a YAML filename.

    E.g., "hist_cor_angio.yaml" -> {"hist", "cor", "coronary", "angio", "angioplasty"}
    """
    stem = filename.replace(".yaml", "").replace("_", " ").lower()
    words = set(stem.split())

    # Expand common abbreviations used in HV filenames
    expansions: dict[str, list[str]] = {
        "cor": ["coronary"],
        "angio": ["angioplasty", "angiography"],
        "sys": ["systolic"],
        "dia": ["diastolic"],
        "bp": ["blood", "pressure"],
        "bdy": ["body"],
        "hgt": ["height"],
        "wgt": ["weight"],
        "bmi": ["bmi"],
        "cig": ["cigarette", "smoking"],
        "smok": ["smoking"],
        "chol": ["cholesterol"],
        "trig": ["triglyceride"],
        "glu": ["glucose"],
        "creat": ["creatinine"],
        "cyst": ["cystatin"],
        "cysc": ["cystatin"],
        "lympho": ["lymphocyte"],
        "leuko": ["leukocyte"],
        "wbc": ["white blood", "leukocyte", "wbc"],
        "rbc": ["red blood"],
        "plt": ["platelet"],
        "hemo": ["hemoglobin"],
        "hgb": ["hemoglobin"],
        "hct": ["hematocrit"],
        "afib": ["atrial", "fibrillation"],
        "pad": ["peripheral", "arterial"],
        "copd": ["copd", "pulmonary", "obstructive"],
        "stroke": ["stroke", "cerebrovascular"],
        "hyperten": ["hypertension", "blood pressure"],
        "diab": ["diabetes"],
        "insulin": ["insulin"],
        "ct": ["count"],
    }
    expanded = set(words)
    for w in words:
        if w in expansions:
            expanded.update(expansions[w])

    return expanded


# ---------------------------------------------------------------------------
# Check 3.9: value_mappings Completeness
# ---------------------------------------------------------------------------


def check_value_mappings_completeness(
    block: dict, block_idx: int, rel_path: str,
    detail_idx: DetailIndex,
) -> list[Finding]:
    """Check 3.9: Flag dbGaP coded values absent from value_mappings."""
    findings: list[Finding] = []
    class_derivs = block.get("class_derivations")
    if not isinstance(class_derivs, dict):
        return findings

    for cls_name, cls_def in class_derivs.items():
        if not isinstance(cls_def, dict):
            continue
        slot_derivs = cls_def.get("slot_derivations")
        if not isinstance(slot_derivs, dict):
            continue
        class_pht = cls_def.get("populated_from", "")

        for slot_name, slot_def in slot_derivs.items():
            if not isinstance(slot_def, dict):
                continue

            # Only check slots that use value_mappings as the sole mechanism
            vm = slot_def.get("value_mappings")
            if not isinstance(vm, dict) or not vm:
                continue

            # Skip if there's also an expr (expr may handle additional logic)
            if slot_def.get("expr"):
                continue

            # Determine source PHV
            pf = slot_def.get("populated_from")
            if not isinstance(pf, str) or not PHV_RE.fullmatch(pf):
                continue

            detail = detail_idx.records.get(pf)
            if not detail or not detail.codes:
                continue

            # Compare: dbGaP codes vs value_mappings keys
            dbgap_codes = set(detail.codes.keys())
            yaml_codes = set(str(k) for k in vm.keys())

            missing = dbgap_codes - yaml_codes
            if not missing:
                continue

            for code in sorted(missing):
                label = detail.codes.get(code, "")
                if SKIP_LABEL_RE.search(label):
                    # Known skip pattern -- downgrade to INFO
                    findings.append(Finding(
                        file=rel_path,
                        block=block_idx,
                        check="3.9",
                        severity="INFO",
                        message=(
                            f"value_mappings on {cls_name}.{slot_name} "
                            f"({pf}) missing dbGaP code '{code}' "
                            f"(\"{label}\") -- likely intentional skip"
                        ),
                    ))
                else:
                    sev = "ERROR" if slot_name in HIGH_IMPACT_SLOTS else "WARNING"
                    findings.append(Finding(
                        file=rel_path,
                        block=block_idx,
                        check="3.9",
                        severity=sev,
                        message=(
                            f"value_mappings on {cls_name}.{slot_name} "
                            f"({pf}) missing dbGaP code '{code}' "
                            f"(\"{label}\") -- possible data loss"
                        ),
                    ))

    return findings


# ---------------------------------------------------------------------------
# Check 3.10: PHV Type <-> Slot Role Compatibility
# ---------------------------------------------------------------------------


def check_phv_type_compatibility(
    block: dict, block_idx: int, rel_path: str,
    detail_idx: DetailIndex,
) -> list[Finding]:
    """Check 3.10: Flag PHVs whose dbGaP type conflicts with slot role."""
    findings: list[Finding] = []
    class_derivs = block.get("class_derivations")
    if not isinstance(class_derivs, dict):
        return findings

    for cls_name, cls_def in class_derivs.items():
        if not isinstance(cls_def, dict):
            continue
        slot_derivs = cls_def.get("slot_derivations")
        if not isinstance(slot_derivs, dict):
            continue

        for slot_name, slot_def in slot_derivs.items():
            if not isinstance(slot_def, dict):
                continue

            # Only check bare populated_from (no expr wrapping)
            pf = slot_def.get("populated_from")
            if not isinstance(pf, str) or not PHV_RE.fullmatch(pf):
                continue
            # Skip if expr is present -- the expression handles conversion
            if slot_def.get("expr"):
                continue
            # Skip if value_mappings -- the mappings handle type conversion
            if slot_def.get("value_mappings"):
                continue

            detail = detail_idx.records.get(pf)
            if not detail:
                continue

            vtype = detail.type.lower()  # e.g., "encoded value", "decimal", "integer"
            unit = (detail.unit or "").lower()

            # Check enum slots fed by numeric types
            if slot_name in ENUM_SLOTS:
                if vtype in ("decimal", "integer", "num"):
                    suggestion = _suggest_adjacent(
                        detail_idx, detail.pht, detail.name,
                        {"encoded value", "encoded"},
                    )
                    msg = (
                        f"{cls_name}.{slot_name} populated_from "
                        f"{pf} ({detail.name}) has type '{detail.type}'"
                    )
                    if "day" in unit:
                        msg += f" with unit '{detail.unit}'"
                    msg += " -- expected 'encoded value' for this slot"
                    if suggestion:
                        msg += f". Did you mean {suggestion}?"
                    findings.append(Finding(
                        file=rel_path,
                        block=block_idx,
                        check="3.10",
                        severity="ERROR",
                        message=msg,
                    ))

            # Check numeric slots fed by encoded types
            if slot_name in NUMERIC_SLOTS:
                if vtype in ("encoded value", "encoded"):
                    suggestion = _suggest_adjacent(
                        detail_idx, detail.pht, detail.name,
                        {"decimal", "integer", "num"},
                    )
                    msg = (
                        f"{cls_name}.{slot_name} populated_from "
                        f"{pf} ({detail.name}) has type '{detail.type}'"
                        f" -- expected numeric type for this slot"
                    )
                    if suggestion:
                        msg += f". Did you mean {suggestion}?"
                    findings.append(Finding(
                        file=rel_path,
                        block=block_idx,
                        check="3.10",
                        severity="ERROR",
                        message=msg,
                    ))

    return findings


def _suggest_adjacent(
    detail_idx: DetailIndex, pht: str, var_name: str,
    compatible_types: set[str],
) -> str | None:
    """Search for a nearby PHV in the same PHT with a compatible type.

    Looks for variables with a name that shares a prefix with the target.
    """
    if not pht or not var_name:
        return None

    # Extract a prefix to match against (first chars before trailing digits)
    prefix = re.sub(r"\d+$", "", var_name)
    if len(prefix) < 2:
        return None

    candidates = []
    for phv, rec in detail_idx.records.items():
        if rec.pht != pht:
            continue
        if rec.name == var_name:
            continue
        if rec.type.lower() not in compatible_types:
            continue
        if rec.name.startswith(prefix):
            candidates.append((phv, rec.name))

    if not candidates:
        return None

    # Return the best match (shortest name difference)
    candidates.sort(key=lambda x: abs(len(x[1]) - len(var_name)))
    phv, name = candidates[0]
    return f"{phv} ({name}, type: {detail_idx.records[phv].type})"


# ---------------------------------------------------------------------------
# Check 3.12: PHV Description <-> Domain Mismatch
# ---------------------------------------------------------------------------


def check_phv_domain_mismatch(
    block: dict, block_idx: int, rel_path: str,
    detail_idx: DetailIndex,
    file_domain: set[str],
) -> list[Finding]:
    """Check 3.12: Flag PHVs whose description conflicts with file domain."""
    findings: list[Finding] = []
    if not file_domain:
        return findings

    class_derivs = block.get("class_derivations")
    if not isinstance(class_derivs, dict):
        return findings

    for cls_name, cls_def in class_derivs.items():
        if not isinstance(cls_def, dict):
            continue
        slot_derivs = cls_def.get("slot_derivations")
        if not isinstance(slot_derivs, dict):
            continue

        for slot_name, slot_def in slot_derivs.items():
            if not isinstance(slot_def, dict):
                continue

            # Collect all PHV refs in this slot
            phvs: list[str] = []
            pf = slot_def.get("populated_from")
            if isinstance(pf, str) and PHV_RE.fullmatch(pf):
                phvs.append(pf)
            expr = slot_def.get("expr")
            if isinstance(expr, str):
                phvs.extend(m.group() for m in PHV_RE.finditer(expr))

            for phv in phvs:
                detail = detail_idx.records.get(phv)
                if not detail:
                    continue

                desc_lower = detail.description.lower()
                desc_words = set(re.findall(r"[a-z]+", desc_lower))

                for domain_a, conflict_b in DOMAIN_CONFLICTS:
                    # Check if file domain overlaps with domain_a
                    if not (file_domain & domain_a):
                        continue
                    # Check if PHV description contains conflict_b terms
                    matched_conflicts = desc_words & conflict_b
                    # Also check multi-word conflict terms
                    for term in conflict_b:
                        if " " in term and term in desc_lower:
                            matched_conflicts.add(term)

                    if matched_conflicts:
                        findings.append(Finding(
                            file=rel_path,
                            block=block_idx,
                            check="3.12",
                            severity="WARNING",
                            message=(
                                f"{cls_name}.{slot_name}: {phv} "
                                f"({detail.name}) description "
                                f"\"{detail.description[:80]}\" contains "
                                f"domain keyword(s) "
                                f"{sorted(matched_conflicts)} -- "
                                f"conflicts with file domain "
                                f"{sorted(file_domain & domain_a)}"
                            ),
                        ))
                        break  # One conflict per PHV is enough

    return findings


# ---------------------------------------------------------------------------
# Check 3.14: unit_conversion Source Unit Mismatch
# ---------------------------------------------------------------------------

# UCUM <-> dbGaP informal unit equivalences.
# Keys: UCUM notation used in YAML source_unit.
# Values: set of equivalent dbGaP unit strings (case-insensitive match).
_UCUM_TO_DBGAP: dict[str, set[str]] = {
    "[lb_av]": {"lb", "lbs", "pounds", "pound"},
    "[in_us]": {"in", "inches", "inch"},
    "[in_i]":  {"in", "inches", "inch"},
    "kg":      {"kg", "kilograms", "kilogram"},
    "cm":      {"cm", "centimeters", "centimeter"},
    "m":       {"m", "meters", "meter"},
    "mm[Hg]":  {"mmhg", "mm hg", "mm(hg)"},
    "mg/dL":   {"mg/dl"},
    "g/dL":    {"g/dl"},
    "mg":      {"mg"},
    "g":       {"g", "gm", "grams", "gram"},
    "mL":      {"ml", "milliliters"},
    "L":       {"l", "liters", "liter"},
    "mm":      {"mm"},
    "%":       {"%", "percent"},
    "ms":      {"ms", "msec", "milliseconds"},
    "s":       {"seconds", "sec", "s"},
    "min":     {"min", "minutes"},
    "d":       {"days", "day", "d"},
    "a":       {"years", "year", "yr"},
    "mo":      {"months", "month"},
    "u[IU]/mL": {"uiu/ml", "uiu/ml", "iu/ml", "miu/ml"},
    "10*3/uL": {"10*3/ul", "1000/ul", "k/ul", "10^3/ul"},
}


def _units_compatible(ucum_unit: str, dbgap_unit: str) -> bool:
    """Check if a UCUM source_unit is compatible with a dbGaP declared unit.

    Returns True if they match (meaning the conversion IS consistent
    with the source unit), or if we can't determine compatibility.
    """
    if not ucum_unit or not dbgap_unit:
        return True  # Can't check -- don't flag

    ucum_clean = ucum_unit.strip().strip("'\"")
    dbgap_lower = dbgap_unit.strip().lower()

    # Direct match (case-insensitive)
    if ucum_clean.lower() == dbgap_lower:
        return True

    # Look up UCUM equivalences
    equivalents = _UCUM_TO_DBGAP.get(ucum_clean)
    if equivalents and dbgap_lower in equivalents:
        return True

    # Reverse check: if dbGaP unit matches the UCUM target_unit, that's
    # a MISMATCH (source is already in target units, conversion is wrong).
    # This case is handled by the caller checking source != dbgap.

    # If the UCUM unit is not in our map, we can't verify -- don't flag
    if ucum_clean not in _UCUM_TO_DBGAP:
        return True

    # UCUM is in our map but dbGaP unit doesn't match any equivalent
    return False


def _walk_slot_derivations(block: dict):
    """Yield (class_name, slot_name, slot_def, parent_pht) for all slot_derivations.

    Handles both top-level class_derivations and nested object_derivations
    (e.g., Quantity inside value_quantity).
    """
    class_derivs = block.get("class_derivations")
    if not isinstance(class_derivs, dict):
        return

    for cls_name, cls_def in class_derivs.items():
        if not isinstance(cls_def, dict):
            continue
        pht = cls_def.get("populated_from")
        slot_derivs = cls_def.get("slot_derivations")
        if isinstance(slot_derivs, dict):
            for slot_name, slot_def in slot_derivs.items():
                if isinstance(slot_def, dict):
                    yield cls_name, slot_name, slot_def, pht
                    # Check nested object_derivations (e.g., Quantity)
                    obj_derivs = slot_def.get("object_derivations")
                    if isinstance(obj_derivs, list):
                        for od in obj_derivs:
                            if not isinstance(od, dict):
                                continue
                            nested_cd = od.get("class_derivations")
                            if not isinstance(nested_cd, dict):
                                continue
                            for ncls, ncls_def in nested_cd.items():
                                if not isinstance(ncls_def, dict):
                                    continue
                                nested_pht = ncls_def.get("populated_from", pht)
                                nested_sd = ncls_def.get("slot_derivations")
                                if isinstance(nested_sd, dict):
                                    for ns_name, ns_def in nested_sd.items():
                                        if isinstance(ns_def, dict):
                                            yield ncls, ns_name, ns_def, nested_pht


def check_unit_conversion_mismatch(
    block: dict, block_idx: int, rel_path: str,
    detail_idx: DetailIndex,
) -> list[Finding]:
    """Check 3.14: unit_conversion source_unit vs dbGaP declared unit.

    When a slot has unit_conversion with source_unit, the declared
    source_unit should match what dbGaP says the variable's unit is.
    If dbGaP says the variable is already in the target unit, the
    conversion would corrupt the data (e.g., halving weights).
    """
    findings: list[Finding] = []

    for cls_name, slot_name, slot_def, parent_pht in _walk_slot_derivations(block):
        uc = slot_def.get("unit_conversion")
        if not isinstance(uc, dict):
            continue

        source_unit = uc.get("source_unit")
        target_unit = uc.get("target_unit")
        if not source_unit:
            continue

        # Find the PHV being converted
        phv = slot_def.get("populated_from")
        if not isinstance(phv, str) or not PHV_RE.fullmatch(phv):
            continue

        detail = detail_idx.records.get(phv)
        if not detail or not detail.unit:
            continue

        dbgap_unit = detail.unit

        # Check: does source_unit match what dbGaP declares?
        if not _units_compatible(source_unit, dbgap_unit):
            # Additional check: is dbGaP unit actually the TARGET unit?
            # This means source is already converted -- critical error.
            target_matches_dbgap = False
            if target_unit:
                target_clean = str(target_unit).strip().strip("'\"").lower()
                if target_clean == dbgap_unit.strip().lower():
                    target_matches_dbgap = True

            if target_matches_dbgap:
                severity = "CRITICAL"
                detail_msg = (
                    f"dbGaP declares unit='{dbgap_unit}' which matches "
                    f"target_unit='{target_unit}' -- source data is ALREADY "
                    f"in the target unit. This conversion will corrupt values"
                )
            else:
                severity = "ERROR"
                detail_msg = (
                    f"dbGaP declares unit='{dbgap_unit}' which does not "
                    f"match source_unit='{source_unit}'"
                )

            findings.append(Finding(
                file=rel_path,
                block=block_idx,
                check="3.14",
                severity=severity,
                message=(
                    f"{cls_name}.{slot_name}: {phv} ({detail.name}) "
                    f"has unit_conversion source_unit='{source_unit}' but "
                    f"{detail_msg}"
                ),
            ))

    return findings


# ---------------------------------------------------------------------------
# Check 3.13: Condition Null-Default Risk (Collection Interval)
# ---------------------------------------------------------------------------

# Matches "Collected in: P1 P2 P3" style values
_COLLECTED_IN_RE = re.compile(r"^Collected\s+in:\s*(.+)$", re.IGNORECASE)

# Sub-phase aliases: if a parent phase is in coll_interval, its sub-phases
# are considered covered.  COPDGene P3B is "Phase 3 Short-term 1-year
# follow-up" -- a sub-visit of P3 that dbGaP rolls into "Collected in: P3".
_PHASE_SUB_ALIASES: dict[str, str] = {
    "P3B": "P3",  # COPDGene Phase 3B -> Phase 3
}


def _expand_ci_phases(ci_phases: set[str]) -> set[str]:
    """Expand collection-interval phases to include known sub-phase aliases."""
    expanded = set(ci_phases)
    for child, parent in _PHASE_SUB_ALIASES.items():
        if parent in ci_phases:
            expanded.add(child)
    return expanded

# Detects case() in expressions
_CASE_RE = re.compile(r"\bcase\s*\(")

# Matches case result strings: , "RESULT") or , 'RESULT')
_CASE_RESULT_DQ = re.compile(r',\s*"([^"]+)"\s*\)')
_CASE_RESULT_SQ = re.compile(r",\s*'([^']+)'\s*\)")


def _parse_ci_phases(coll_interval: str | None) -> set[str] | None:
    """Parse structured coll_interval into phase tokens, or None."""
    if not coll_interval:
        return None
    m = _COLLECTED_IN_RE.match(coll_interval.strip())
    if not m:
        return None
    tokens = m.group(1).split()
    return set(tokens) if tokens else None


def _extract_case_phases(expr: str) -> set[str]:
    """Extract visit phase tokens from a case() expression's result strings.

    E.g., case((..., 'COPDGene P1'), (..., 'COPDGene P2')) -> {'P1', 'P2'}
    """
    labels = _CASE_RESULT_DQ.findall(expr) + _CASE_RESULT_SQ.findall(expr)
    phases: set[str] = set()
    for label in labels:
        parts = label.strip().split()
        if len(parts) >= 2:
            token = parts[-1]
            if token != "None":
                phases.add(token)
    return phases


def check_condition_null_default(
    block: dict, block_idx: int, rel_path: str,
    detail_idx: DetailIndex,
) -> list[Finding]:
    """Check 3.13: Condition null-default risk from collection interval mismatch.

    For Condition class blocks that use value_mappings on condition_status:
    if the associated_visit case expression routes to phases where the
    condition_status source PHV is NOT collected (per coll_interval), the
    pipeline will see null and may default to ABSENT -- producing false
    negatives that look like valid data.

    This is a CRITICAL severity finding because the output is actively
    misleading (plausible enum value from null input).
    """
    findings: list[Finding] = []
    class_derivs = block.get("class_derivations")
    if not isinstance(class_derivs, dict):
        return findings

    for cls_name, cls_def in class_derivs.items():
        if cls_name != "Condition" or not isinstance(cls_def, dict):
            continue

        slot_derivs = cls_def.get("slot_derivations")
        if not isinstance(slot_derivs, dict):
            continue

        # Must have a case()-based associated_visit
        visit_slot = slot_derivs.get("associated_visit", {})
        if not isinstance(visit_slot, dict):
            continue
        visit_expr = visit_slot.get("expr")
        if not visit_expr or not _CASE_RE.search(str(visit_expr)):
            continue

        # Extract the phases from the visit case expression
        case_phases = _extract_case_phases(str(visit_expr))
        if not case_phases:
            continue

        # Find the condition_status PHV
        status_slot = slot_derivs.get("condition_status", {})
        if not isinstance(status_slot, dict):
            continue

        # Needs value_mappings (the pattern where null -> ABSENT happens)
        if not status_slot.get("value_mappings"):
            continue

        pf = status_slot.get("populated_from")
        if not isinstance(pf, str) or not PHV_RE.fullmatch(pf):
            continue

        detail = detail_idx.records.get(pf)
        if not detail or not detail.coll_interval:
            continue

        ci_phases = _parse_ci_phases(detail.coll_interval)
        if ci_phases is None:
            continue

        # Expand ci_phases with known sub-phase aliases
        # (e.g., P3 covers P3B in COPDGene)
        ci_expanded = _expand_ci_phases(ci_phases)

        uncovered = case_phases - ci_expanded
        if not uncovered:
            continue

        uncovered_str = ", ".join(sorted(uncovered))
        covered_str = ", ".join(sorted(ci_phases))

        findings.append(Finding(
            file=rel_path,
            block=block_idx,
            check="3.13",
            severity="CRITICAL",
            message=(
                f"Condition.condition_status ({pf}, {detail.name}) "
                f"is only collected at [{covered_str}] but visit case "
                f"routes to [{uncovered_str}] -- null "
                f"condition_status may default to ABSENT, producing "
                f"false negatives"
            ),
        ))

    return findings


# ---------------------------------------------------------------------------
# Check 3.15: Phantom Code Detection
# ---------------------------------------------------------------------------


def check_phantom_codes(
    block: dict, block_idx: int, rel_path: str,
    detail_idx: DetailIndex,
) -> list[Finding]:
    """Check 3.15: Flag value_mappings keys that don't exist in dbGaP coded values.

    Inverse of rule 3.9. Rule 3.9 catches dbGaP codes MISSING from YAML;
    this rule catches YAML codes that don't exist in dbGaP -- indicating a
    typo, copy-paste from another cohort, or stale value from a version
    migration.
    """
    findings: list[Finding] = []
    class_derivs = block.get("class_derivations")
    if not isinstance(class_derivs, dict):
        return findings

    for cls_name, cls_def in class_derivs.items():
        if not isinstance(cls_def, dict):
            continue
        slot_derivs = cls_def.get("slot_derivations")
        if not isinstance(slot_derivs, dict):
            continue

        for slot_name, slot_def in slot_derivs.items():
            if not isinstance(slot_def, dict):
                continue

            vm = slot_def.get("value_mappings")
            if not isinstance(vm, dict) or not vm:
                continue

            # Skip if there's also an expr (expr may handle additional logic)
            if slot_def.get("expr"):
                continue

            # Determine source PHV
            pf = slot_def.get("populated_from")
            if not isinstance(pf, str) or not PHV_RE.fullmatch(pf):
                continue

            detail = detail_idx.records.get(pf)
            if not detail or not detail.codes:
                continue

            # Compare: YAML keys vs dbGaP codes
            dbgap_codes = set(detail.codes.keys())
            yaml_codes = set(str(k) for k in vm.keys())

            phantom = yaml_codes - dbgap_codes
            if not phantom:
                continue

            for code in sorted(phantom):
                sev = "ERROR" if slot_name in HIGH_IMPACT_SLOTS else "WARNING"
                findings.append(Finding(
                    file=rel_path,
                    block=block_idx,
                    check="3.15",
                    severity=sev,
                    message=(
                        f"value_mappings on {cls_name}.{slot_name} "
                        f"({pf}) has code '{code}' which does not exist "
                        f"in dbGaP coded values for {detail.name} -- "
                        f"possible typo or cross-cohort copy-paste error. "
                        f"Valid codes: {sorted(dbgap_codes)}"
                    ),
                ))

    return findings


# ---------------------------------------------------------------------------
# Check 3.16: Quantity Missing Unit
# ---------------------------------------------------------------------------


def check_quantity_missing_unit(
    block: dict, block_idx: int, rel_path: str,
) -> list[Finding]:
    """Check 3.16: Flag Quantity blocks with value_decimal/value_integer but no unit.

    Walks object_derivations looking for Quantity class definitions that
    contain a numeric value slot but lack a sibling 'unit' slot. A Quantity
    without a unit is semantically incomplete -- downstream consumers cannot
    interpret the numeric value.

    Also checks top-level class_derivations named 'Quantity'.
    """
    findings: list[Finding] = []

    def _check_quantity_slots(
        cls_name: str, cls_def: dict, parent_slot: str,
    ) -> None:
        """Check a single Quantity class definition for missing unit."""
        slot_derivs = cls_def.get("slot_derivations")
        if not isinstance(slot_derivs, dict):
            return

        has_numeric = any(
            s in slot_derivs for s in ("value_decimal", "value_integer")
        )
        has_unit = "unit" in slot_derivs

        if has_numeric and not has_unit:
            numeric_slot = (
                "value_decimal" if "value_decimal" in slot_derivs
                else "value_integer"
            )
            context = f" (in {parent_slot})" if parent_slot else ""
            findings.append(Finding(
                file=rel_path,
                block=block_idx,
                check="3.16",
                severity="WARNING",
                message=(
                    f"{cls_name}{context} has {numeric_slot} but no "
                    f"unit slot -- Quantity without unit is semantically "
                    f"incomplete"
                ),
            ))

    # Walk top-level class_derivations
    class_derivs = block.get("class_derivations")
    if not isinstance(class_derivs, dict):
        return findings

    for cls_name, cls_def in class_derivs.items():
        if not isinstance(cls_def, dict):
            continue

        # Check if this IS a Quantity class at top level
        if cls_name == "Quantity":
            _check_quantity_slots(cls_name, cls_def, "")

        # Walk slot_derivations looking for object_derivations with Quantity
        slot_derivs = cls_def.get("slot_derivations")
        if not isinstance(slot_derivs, dict):
            continue

        for slot_name, slot_def in slot_derivs.items():
            if not isinstance(slot_def, dict):
                continue
            obj_derivs = slot_def.get("object_derivations")
            if not isinstance(obj_derivs, list):
                continue
            for od in obj_derivs:
                if not isinstance(od, dict):
                    continue
                nested_cd = od.get("class_derivations")
                if not isinstance(nested_cd, dict):
                    continue
                for ncls_name, ncls_def in nested_cd.items():
                    if not isinstance(ncls_def, dict):
                        continue
                    if ncls_name == "Quantity":
                        _check_quantity_slots(
                            ncls_name, ncls_def,
                            f"{cls_name}.{slot_name}",
                        )

    return findings


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="HV-Lint Phase 3: Semantic validation (3.9, 3.10, 3.12-3.16)"
    )
    p.add_argument(
        "--cache-dir", required=True,
        help="Directory containing per-cohort *_detail.json.gz indexes"
    )
    p.add_argument(
        "--cohort", default="all",
        help="Cohort to validate or 'all' (default: all)"
    )
    p.add_argument(
        "--fail-on", default="error",
        choices=["critical", "error", "high", "warning", "info"],
        help="Minimum severity for non-zero exit (default: error)"
    )
    p.add_argument(
        "--check", nargs="*", default=None,
        choices=["3.9", "3.10", "3.12", "3.13", "3.14", "3.15", "3.16"],
        help="Run only specific checks (default: all)"
    )
    return p.parse_args()


def main() -> int:
    args = parse_args()
    in_ci = os.environ.get("GITHUB_ACTIONS") == "true"
    cache_dir = Path(args.cache_dir)
    enabled_checks = set(args.check) if args.check else {"3.9", "3.10", "3.12", "3.13", "3.14", "3.15", "3.16"}

    if not cache_dir.is_dir():
        print(f"ERROR: Cache directory not found: {cache_dir}", file=sys.stderr)
        print("Run build_phv_detail_index.py first.", file=sys.stderr)
        return 1

    # Load detail indexes
    indexes: dict[str, DetailIndex] = {}
    cohort_upper = args.cohort.upper()
    needed = (
        {k: v for k, v in COHORT_TO_CACHE_KEY.items() if k.upper() == cohort_upper}
        if cohort_upper != "ALL"
        else COHORT_TO_CACHE_KEY
    )
    for cohort_name, cache_key in needed.items():
        try:
            indexes[cohort_name] = load_detail_index(cache_dir, cache_key)
            count = len(indexes[cohort_name].records)
            coded = sum(1 for r in indexes[cohort_name].records.values() if r.codes)
            print(f"  Loaded {cohort_name}: {count:,} PHVs ({coded:,} coded)")
        except FileNotFoundError:
            pass

    if not indexes:
        print("ERROR: No detail indexes found. Run build_phv_detail_index.py.",
              file=sys.stderr)
        return 1

    # Discover YAML files
    base_dir = find_transform_dir()
    hv_root = base_dir.parent
    yaml_files = find_yaml_files(base_dir, args.cohort)
    if not yaml_files:
        print(f"No YAML files found under {base_dir}")
        return 0

    print(f"Found {len(yaml_files)} YAML files to validate")
    print(f"Enabled checks: {', '.join(sorted(enabled_checks))}")

    # Run checks
    all_findings: list[Finding] = []
    files_checked = 0
    blocks_checked = 0

    for file_path in yaml_files:
        rel_path = file_path.relative_to(hv_root).as_posix()

        cohort = detect_cohort(file_path)
        if cohort not in indexes:
            continue

        try:
            with file_path.open(encoding="utf-8") as f:
                data = yaml.safe_load(f)
        except (OSError, yaml.YAMLError):
            continue

        if data is None:
            continue

        blocks = data if isinstance(data, list) else [data]
        files_checked += 1
        detail_idx = indexes[cohort]

        # Pre-compute file domain for 3.12
        file_domain = _filename_domain_keywords(file_path.name)

        for idx, block in enumerate(blocks):
            blocks_checked += 1
            if not isinstance(block, dict):
                continue

            if "3.9" in enabled_checks:
                all_findings.extend(
                    check_value_mappings_completeness(
                        block, idx, rel_path, detail_idx
                    )
                )
            if "3.10" in enabled_checks:
                all_findings.extend(
                    check_phv_type_compatibility(
                        block, idx, rel_path, detail_idx
                    )
                )
            if "3.12" in enabled_checks:
                all_findings.extend(
                    check_phv_domain_mismatch(
                        block, idx, rel_path, detail_idx, file_domain
                    )
                )
            if "3.13" in enabled_checks:
                all_findings.extend(
                    check_condition_null_default(
                        block, idx, rel_path, detail_idx
                    )
                )
            if "3.14" in enabled_checks:
                all_findings.extend(
                    check_unit_conversion_mismatch(
                        block, idx, rel_path, detail_idx
                    )
                )
            if "3.15" in enabled_checks:
                all_findings.extend(
                    check_phantom_codes(
                        block, idx, rel_path, detail_idx
                    )
                )
            if "3.16" in enabled_checks:
                all_findings.extend(
                    check_quantity_missing_unit(
                        block, idx, rel_path,
                    )
                )

    # Report
    fail_rank = SEVERITY_RANK[args.fail_on.upper()]

    counts: dict[str, int] = {}
    for f in all_findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1

    findings_by_file: dict[str, list[Finding]] = {}
    for f in all_findings:
        findings_by_file.setdefault(f.file, []).append(f)

    print(f"\n{'='*70}")
    print("HV-Lint Phase 3: Semantic Validation Results")
    print(f"{'='*70}")
    print(f"Files checked:  {files_checked}")
    print(f"Blocks checked: {blocks_checked}")

    parts = []
    for sev in ("CRITICAL", "ERROR", "HIGH", "WARNING", "INFO"):
        if counts.get(sev, 0) > 0:
            parts.append(f"{counts[sev]} {sev}")
    if parts:
        print(f"Findings:       {', '.join(parts)}")
    else:
        print("Findings:       None -- all semantic checks passed!")

    if findings_by_file:
        print(f"\n{'-'*70}")
        for fpath in sorted(findings_by_file):
            short = fpath.replace("priority_variables_transform/", "")
            print(f"\n{short}:")
            for f in sorted(findings_by_file[fpath], key=lambda x: (x.block, x.check)):
                print(f.terminal_line())
                if in_ci:
                    print(f.gh_annotation())

    blocking = [
        f for f in all_findings
        if SEVERITY_RANK.get(f.severity, 0) >= fail_rank
    ]
    if blocking:
        print(f"\nFAILED: {len(blocking)} findings at or above '{args.fail_on}'")
        return 1
    if all_findings:
        print(f"\nPASSED (with {len(all_findings)} advisory findings below fail threshold)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
