#!/usr/bin/env python3
"""HV-Lint Phase 3: dbGaP cross-reference validation for HV YAML files.

Validates that PHV and PHT accessions referenced in transformation YAML
files actually exist in the dbGaP variable index and have correct
table membership.

Requires a pre-built compressed index (generated by build_phv_index.py).

Usage:
    python hv-lint/phase-3/validate_dbgap_crossref.py --cache-dir hv-lint/dbgap-cache
    python hv-lint/phase-3/validate_dbgap_crossref.py --cache-dir hv-lint/dbgap-cache --cohort ARIC

Checks implemented:
    3.1  PHV/PHT accession format -- malformed accessions flagged
    3.2  PHT existence -- referenced PHTs must exist in dbGaP index
    3.3  PHV existence -- referenced PHVs must exist in dbGaP index
    3.4  PHV-to-PHT membership -- PHVs must belong to the declared table
    3.5  Cross-table reference -- PHV from a different table without joins
"""

from __future__ import annotations

import argparse
import gzip
import json
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

# Path resolution -- works in both control center and HV repo
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from _paths import find_transform_dir  # noqa: E402

import yaml

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Maps directory-derived cohort name -> dbGaP cache key
COHORT_TO_CACHE_KEY: dict[str, str] = {
    "ARIC": "aric",
    "CARDIA": "cardia",
    "CHS": "chs",
    "COPDGene": "copdgene",
    "FHS": "fhs",
    "HCHS": "hchs_sol",
    "JHS": "jhs",
    "MESA": "mesa",
    "SPIROMICS": "spiromics",
    "WHI": "whi",
    "LTRC": "ltrc",
}

# Files to skip entirely (reset -- start fresh for Phase 3 restructuring)
KNOWN_ISSUES: dict[str, str] = {}

SEVERITY_RANK = {"CRITICAL": 5, "ERROR": 4, "HIGH": 3, "WARNING": 2, "INFO": 1}

# Slots that routinely reference a different table (e.g.,
# associated_participant always comes from the subject table,
# age_at_* slots reference the visit/age table).
EXPECTED_CROSS_TABLE_SLOTS = {
    "associated_participant", "associated_visit",
}
# Slot name prefixes where cross-table references are normal
EXPECTED_CROSS_TABLE_PREFIXES = (
    "age_at_", "age_of_",
)

# ---------------------------------------------------------------------------
# Accession format regexes
# ---------------------------------------------------------------------------

# Strict format: the canonical dbGaP accession pattern
PHV_STRICT_RE = re.compile(r"phv\d{8}(?!\d)")
PHT_STRICT_RE = re.compile(r"pht\d{6}(?!\d)")

# Loose format: catches anything that looks like a PHV/PHT but may have
# wrong digit count -- used by check 3.1 to detect malformed accessions
PHV_LOOSE_RE = re.compile(r"phv\d+")
PHT_LOOSE_RE = re.compile(r"pht\d+")

# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class Finding:
    file: str
    block: int
    check: str       # e.g., "3.1"
    severity: str    # CRITICAL, ERROR, WARNING, INFO
    message: str

    @staticmethod
    def _esc_prop(text: str) -> str:
        """Escape a workflow-command *property* value (file=, line=, ...)."""
        return (text.replace("%", "%25").replace("\r", "%0D")
                .replace("\n", "%0A").replace(":", "%3A").replace(",", "%2C"))

    @staticmethod
    def _esc_msg(text: str) -> str:
        """Escape a workflow-command *message* (colons/commas stay readable)."""
        return text.replace("%", "%25").replace("\r", "%0D").replace("\n", "%0A")

    def gh_annotation(self) -> str:
        level = {
            "CRITICAL": "error", "ERROR": "error",
            "WARNING": "warning", "HIGH": "warning", "INFO": "notice",
        }.get(self.severity, "notice")
        return f"::{level} file={self._esc_prop(self.file)}::HV-Lint [{self.check}] {self._esc_msg(self.message)} (block {self.block})"

    def terminal_line(self) -> str:
        sev = self.severity[:5].ljust(5)
        return f"  {sev}  block {self.block:>3}  [{self.check}] {self.message}"


@dataclass
class DbGaPIndex:
    """Pre-built dbGaP index for a single cohort."""
    phv_to_pht: dict[str, str] = field(default_factory=dict)  # phv -> pht
    valid_phts: set[str] = field(default_factory=set)

# ---------------------------------------------------------------------------
# Index loading
# ---------------------------------------------------------------------------

def load_dbgap_index(cache_dir: Path, cache_key: str) -> DbGaPIndex:
    """Load compressed phv->pht index for a cohort."""
    gz_path = cache_dir / f"{cache_key}.json.gz"
    json_path = cache_dir / f"{cache_key}.json"

    if gz_path.exists():
        with gzip.open(gz_path, "rt", encoding="utf-8") as f:
            mapping = json.load(f)
    elif json_path.exists():
        with json_path.open(encoding="utf-8") as f:
            mapping = json.load(f)
    else:
        raise FileNotFoundError(
            f"No dbGaP index for '{cache_key}': "
            f"expected {gz_path} or {json_path}"
        )

    idx = DbGaPIndex()
    idx.phv_to_pht = mapping
    idx.valid_phts = set(mapping.values())
    return idx

# ---------------------------------------------------------------------------
# File discovery
# ---------------------------------------------------------------------------

def find_yaml_files(base_dir: Path, cohort: str) -> list[Path]:
    files = sorted(
        f for f in base_dir.rglob("*.yaml")
        if any("-ingest" in part for part in f.parts)
        and not f.name.endswith(".swp")
    )
    if cohort.lower() != "all":
        pattern = f"{cohort}-ingest".lower()
        files = [f for f in files if pattern in str(f).lower()]
    return files


def detect_cohort(file_path: Path) -> str:
    for part in file_path.parts:
        if part.endswith("-ingest"):
            return part.replace("-ingest", "")
    return "UNKNOWN"

# ---------------------------------------------------------------------------
# Reference extraction
# ---------------------------------------------------------------------------

def extract_slot_refs(
    slot_derivs: dict, class_name: str
) -> tuple[list[tuple[str, str]], set[str]]:
    """Extract PHV references and join PHTs from slot_derivations.

    Returns:
        phv_refs: list of (phv, "slot_name on ClassName")
        join_phts: set of PHTs declared via joins
    """
    phv_refs_seen: set[tuple[str, str]] = set()
    phv_refs: list[tuple[str, str]] = []
    join_phts: set[str] = set()

    def _add_ref(phv: str, context: str) -> None:
        key = (phv, context)
        if key not in phv_refs_seen:
            phv_refs_seen.add(key)
            phv_refs.append(key)

    if not isinstance(slot_derivs, dict):
        return phv_refs, join_phts

    for slot_name, slot_def in slot_derivs.items():
        if not isinstance(slot_def, dict):
            continue

        # Direct populated_from
        pf = slot_def.get("populated_from")
        if isinstance(pf, str) and PHV_STRICT_RE.fullmatch(pf):
            _add_ref(pf, f"{slot_name} on {class_name}")

        # PHVs in expr (within {phv...} or plain references)
        expr = slot_def.get("expr")
        if isinstance(expr, str):
            for m in PHV_STRICT_RE.finditer(expr):
                _add_ref(m.group(), f"expr in {slot_name} on {class_name}")

        # PHVs in value_mappings keys
        vm = slot_def.get("value_mappings")
        if isinstance(vm, dict):
            for k in vm:
                if isinstance(k, str):
                    for m in PHV_STRICT_RE.finditer(k):
                        _add_ref(m.group(), f"value_mappings key in {slot_name} on {class_name}")

        # PHVs in expression_to_value_mappings keys
        evm = slot_def.get("expression_to_value_mappings")
        if isinstance(evm, dict):
            for k in evm:
                if isinstance(k, str):
                    for m in PHV_STRICT_RE.finditer(k):
                        _add_ref(m.group(), f"expression_to_value_mappings in {slot_name} on {class_name}")

        # Recurse into object_derivations
        od_list = slot_def.get("object_derivations") or []
        if not isinstance(od_list, list):
            od_list = []
        for od in od_list:
            if isinstance(od, dict) and "class_derivations" in od:
                nested_cd = od["class_derivations"]
                if not isinstance(nested_cd, dict):
                    continue
                for nested_cls, nested_def in nested_cd.items():
                    if isinstance(nested_def, dict):
                        nested_slots = nested_def.get("slot_derivations")
                        nested_slots = nested_slots if isinstance(nested_slots, dict) else {}
                        nested_phvs, nested_joins = extract_slot_refs(nested_slots, nested_cls)
                        for ref in nested_phvs:
                            if ref not in phv_refs_seen:
                                phv_refs_seen.add(ref)
                                phv_refs.append(ref)
                        join_phts.update(nested_joins)

                        # Nested class populated_from PHT
                        npht = nested_def.get("populated_from")
                        if isinstance(npht, str) and PHT_STRICT_RE.fullmatch(npht):
                            join_phts.add(npht)

    return phv_refs, join_phts


# ---------------------------------------------------------------------------
# Check 3.1: Accession format validation
# ---------------------------------------------------------------------------

def _collect_accession_strings(block: dict) -> list[tuple[str, str]]:
    """Collect all string values that look like PHV/PHT accessions.

    Returns list of (accession_string, context_description).
    Uses loose regex to catch malformed accessions that the strict
    regex would silently skip.
    """
    results: list[tuple[str, str]] = []
    class_derivs = block.get("class_derivations")
    if not isinstance(class_derivs, dict):
        return results

    for class_name, class_def in class_derivs.items():
        if not isinstance(class_def, dict):
            continue

        # Class populated_from (PHT)
        pf = class_def.get("populated_from")
        if isinstance(pf, str):
            for m in PHT_LOOSE_RE.finditer(pf):
                results.append((m.group(), f"populated_from on {class_name}"))
            for m in PHV_LOOSE_RE.finditer(pf):
                results.append((m.group(), f"populated_from on {class_name}"))

        # Joins populated_from (PHT)
        raw_joins = class_def.get("joins")
        if isinstance(raw_joins, list):
            for j in raw_joins:
                if isinstance(j, dict):
                    jpf = j.get("populated_from")
                    if isinstance(jpf, str):
                        for m in PHT_LOOSE_RE.finditer(jpf):
                            results.append((m.group(), f"joins on {class_name}"))

        # Walk slot_derivations
        slot_derivs = class_def.get("slot_derivations")
        if isinstance(slot_derivs, dict):
            results.extend(_collect_slot_accessions(slot_derivs, class_name))

    return results


def _collect_slot_accessions(
    slot_derivs: dict, class_name: str
) -> list[tuple[str, str]]:
    """Collect accession-like strings from slot_derivations."""
    results: list[tuple[str, str]] = []
    for slot_name, slot_def in slot_derivs.items():
        if not isinstance(slot_def, dict):
            continue

        pf = slot_def.get("populated_from")
        if isinstance(pf, str):
            for m in PHV_LOOSE_RE.finditer(pf):
                results.append((m.group(), f"{slot_name} on {class_name}"))

        expr = slot_def.get("expr")
        if isinstance(expr, str):
            for m in PHV_LOOSE_RE.finditer(expr):
                results.append((m.group(), f"expr in {slot_name} on {class_name}"))

        for key_name in ("value_mappings", "expression_to_value_mappings"):
            mapping = slot_def.get(key_name)
            if isinstance(mapping, dict):
                for k in mapping:
                    if isinstance(k, str):
                        for m in PHV_LOOSE_RE.finditer(k):
                            results.append((m.group(), f"{key_name} in {slot_name} on {class_name}"))

        # Recurse into object_derivations
        od_list = slot_def.get("object_derivations") or []
        if not isinstance(od_list, list):
            od_list = []
        for od in od_list:
            if isinstance(od, dict) and "class_derivations" in od:
                nested_cd = od["class_derivations"]
                if isinstance(nested_cd, dict):
                    for nested_cls, nested_def in nested_cd.items():
                        if isinstance(nested_def, dict):
                            npf = nested_def.get("populated_from")
                            if isinstance(npf, str):
                                for m in PHT_LOOSE_RE.finditer(npf):
                                    results.append((m.group(), f"nested populated_from on {nested_cls}"))
                            nested_slots = nested_def.get("slot_derivations")
                            if isinstance(nested_slots, dict):
                                results.extend(_collect_slot_accessions(nested_slots, nested_cls))
    return results


def check_accession_format(
    block: dict, block_idx: int, rel_path: str
) -> list[Finding]:
    """Check 3.1: Flag accession strings that don't match canonical format."""
    findings: list[Finding] = []
    seen: set[tuple[str, str]] = set()

    for accession, context in _collect_accession_strings(block):
        key = (accession, context)
        if key in seen:
            continue
        seen.add(key)

        if accession.startswith("phv"):
            if not PHV_STRICT_RE.fullmatch(accession):
                findings.append(Finding(
                    rel_path, block_idx, "3.1", "ERROR",
                    f"Malformed PHV '{accession}' ({context}) -- "
                    f"expected phv + exactly 8 digits"
                ))
        elif accession.startswith("pht"):
            if not PHT_STRICT_RE.fullmatch(accession):
                findings.append(Finding(
                    rel_path, block_idx, "3.1", "ERROR",
                    f"Malformed PHT '{accession}' ({context}) -- "
                    f"expected pht + exactly 6 digits"
                ))

    return findings


# ---------------------------------------------------------------------------
# Checks 3.2-3.5
# ---------------------------------------------------------------------------

def check_block(
    block: dict, block_idx: int, rel_path: str,
    dbgap: DbGaPIndex
) -> list[Finding]:
    """Run checks 3.2-3.5 on a single block."""
    findings: list[Finding] = []
    class_derivs = block.get("class_derivations")
    if not isinstance(class_derivs, dict):
        return findings

    for class_name, class_def in class_derivs.items():
        if not isinstance(class_def, dict):
            continue

        raw_pht = class_def.get("populated_from", "")
        class_pht = raw_pht if isinstance(raw_pht, str) and PHT_STRICT_RE.fullmatch(raw_pht) else ""
        raw_joins = class_def.get("joins")
        has_joins = isinstance(raw_joins, list)
        if raw_joins is not None and not has_joins:
            findings.append(Finding(
                rel_path, block_idx, "3.0", "ERROR",
                f"{class_name} joins is "
                f"{type(raw_joins).__name__}, expected list"
            ))
        slot_derivs = class_def.get("slot_derivations")
        if not isinstance(slot_derivs, dict):
            if slot_derivs is not None:
                findings.append(Finding(
                    rel_path, block_idx, "3.0", "ERROR",
                    f"{class_name} slot_derivations is "
                    f"{type(slot_derivs).__name__}, expected mapping"
                ))
            slot_derivs = {}

        # Collect join PHTs for cross-table detection
        join_phts: set[str] = set()
        if has_joins:
            for j in class_def["joins"]:
                if isinstance(j, dict):
                    jpht = j.get("populated_from", "")
                    if isinstance(jpht, str) and PHT_STRICT_RE.fullmatch(jpht):
                        join_phts.add(jpht)

        # -- Check 3.2: PHT existence --
        if class_pht and class_pht not in dbgap.valid_phts:
            findings.append(Finding(
                rel_path, block_idx, "3.2", "ERROR",
                f"PHT '{class_pht}' on {class_name} not found in "
                f"dbGaP variable index"
            ))

        # Extract PHV references from slot derivations
        phv_refs, nested_join_phts = extract_slot_refs(slot_derivs, class_name)
        join_phts.update(nested_join_phts)

        # Track which non-class PHTs are reachable via joins
        all_reachable_phts = ({class_pht} if class_pht else set()) | join_phts

        for phv, context in phv_refs:
            # -- Check 3.3: PHV existence --
            if phv not in dbgap.phv_to_pht:
                findings.append(Finding(
                    rel_path, block_idx, "3.3", "ERROR",
                    f"PHV '{phv}' ({context}) not found in dbGaP index"
                ))
                continue

            actual_pht = dbgap.phv_to_pht[phv]

            # -- Check 3.4 / 3.5: PHV-to-PHT membership --
            if not class_pht:
                continue
            if actual_pht != class_pht:
                # Determine the slot name from context string
                slot_in_context = context.split(" on ")[0] if " on " in context else ""
                # For "expr in slot_name" patterns, extract the actual slot
                bare_slot = slot_in_context.replace("expr in ", "").replace(
                    "value_mappings key in ", ""
                ).replace("expression_to_value_mappings in ", "")

                if actual_pht in all_reachable_phts:
                    # Cross-table but covered by a join
                    findings.append(Finding(
                        rel_path, block_idx, "3.4", "INFO",
                        f"PHV '{phv}' ({context}) belongs to {actual_pht}, "
                        f"not class PHT {class_pht} (covered by joins)"
                    ))
                elif (bare_slot in EXPECTED_CROSS_TABLE_SLOTS
                      or any(bare_slot.startswith(pfx) for pfx in EXPECTED_CROSS_TABLE_PREFIXES)):
                    # Expected cross-table pattern
                    findings.append(Finding(
                        rel_path, block_idx, "3.4", "INFO",
                        f"PHV '{phv}' ({context}) belongs to {actual_pht}, "
                        f"not class PHT {class_pht} (expected cross-table)"
                    ))
                else:
                    # Unexpected cross-table reference
                    findings.append(Finding(
                        rel_path, block_idx, "3.5", "WARNING",
                        f"PHV '{phv}' ({context}) belongs to {actual_pht}, "
                        f"not class PHT {class_pht} - possible cross-table "
                        f"reference without joins"
                    ))

    return findings


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="HV-Lint Phase 3: dbGaP cross-reference validation"
    )
    p.add_argument(
        "--cache-dir",
        required=True,
        help="Directory containing per-cohort .json.gz indexes"
    )
    p.add_argument(
        "--cohort", default="all",
        help="Cohort to validate (e.g., ARIC, CHS) or 'all' (default: all)"
    )
    p.add_argument(
        "--fail-on", default="error",
        choices=["critical", "error", "high", "warning", "info"],
        help="Minimum severity to cause non-zero exit (default: error)"
    )
    p.add_argument(
        "--summary-file", default=None,
        help="Write a Markdown summary table to this file (for GITHUB_STEP_SUMMARY)"
    )
    p.add_argument(
        "--summary-limit", type=int, default=50,
        help="Max findings to include in the Markdown summary (default: 50)"
    )
    return p.parse_args()


def main() -> int:
    args = parse_args()
    in_ci = os.environ.get("GITHUB_ACTIONS") == "true"
    cache_dir = Path(args.cache_dir)

    if not cache_dir.is_dir():
        print(f"ERROR: Cache directory not found: {cache_dir}", file=sys.stderr)
        print("Run build_phv_index.py first to generate the indexes.", file=sys.stderr)
        return 1

    # Load indexes (only the needed cohort when filtering)
    indexes: dict[str, DbGaPIndex] = {}
    cohort_upper = args.cohort.upper()
    needed = (
        {k: v for k, v in COHORT_TO_CACHE_KEY.items() if k.upper() == cohort_upper}
        if cohort_upper != "ALL"
        else COHORT_TO_CACHE_KEY
    )
    for cohort_name, cache_key in needed.items():
        try:
            indexes[cohort_name] = load_dbgap_index(cache_dir, cache_key)
            count = len(indexes[cohort_name].phv_to_pht)
            phts = len(indexes[cohort_name].valid_phts)
            print(f"  Loaded {cohort_name}: {count:,} PHVs across {phts} PHTs")
        except FileNotFoundError:
            pass  # cohort not available -- will skip files for it

    if not indexes:
        print("ERROR: No dbGaP indexes found. Run build_phv_index.py.", file=sys.stderr)
        return 1

    # Discover YAML files
    base_dir = find_transform_dir()
    hv_root = base_dir.parent
    yaml_files = find_yaml_files(base_dir, args.cohort)
    if not yaml_files:
        print(f"No YAML files found under {base_dir}")
        return 1
    print(f"Found {len(yaml_files)} YAML files to validate")

    # Run checks
    all_findings: list[Finding] = []
    files_checked = 0
    blocks_checked = 0
    skipped_no_index: list[str] = []

    for file_path in yaml_files:
        rel_path = file_path.relative_to(hv_root).as_posix()

        if rel_path in KNOWN_ISSUES:
            continue

        cohort = detect_cohort(file_path)
        if cohort not in indexes:
            skipped_no_index.append(rel_path)
            continue

        try:
            with file_path.open(encoding="utf-8") as f:
                data = yaml.safe_load(f)
        except (OSError, yaml.YAMLError) as exc:
            all_findings.append(Finding(
                check="3.0", severity="ERROR",
                file=rel_path, block=0,
                message=f"Cannot parse YAML: {exc}",
            ))
            continue

        if data is None:
            continue

        blocks = data if isinstance(data, list) else [data]
        files_checked += 1
        dbgap = indexes[cohort]

        for idx, block in enumerate(blocks):
            blocks_checked += 1
            if not isinstance(block, dict):
                continue
            # Check 3.1: accession format
            all_findings.extend(check_accession_format(block, idx, rel_path))
            # Checks 3.2-3.5: existence and membership
            all_findings.extend(check_block(block, idx, rel_path, dbgap))

    # -----------------------------------------------------------------------
    # Report
    # -----------------------------------------------------------------------
    # Surface missing-index skips as ERROR findings before building report
    if skipped_no_index:
        for skipped_file in skipped_no_index:
            all_findings.append(Finding(
                check="3.0", severity="ERROR",
                file=skipped_file, block=0,
                message="No dbGaP index available for cohort -- file not validated",
            ))

    fail_rank = SEVERITY_RANK[args.fail_on.upper()]

    counts: dict[str, int] = {}
    for f in all_findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1

    findings_by_file: dict[str, list[Finding]] = {}
    for f in all_findings:
        findings_by_file.setdefault(f.file, []).append(f)

    print(f"\n{'='*70}")
    print("HV-Lint Phase 3 Results")
    print(f"{'='*70}")
    print(f"Files checked:  {files_checked}")
    print(f"Blocks checked: {blocks_checked}")
    if skipped_no_index:
        print(f"Files skipped (no index): {len(skipped_no_index)}")

    parts = []
    for sev in ("CRITICAL", "ERROR", "HIGH", "WARNING", "INFO"):
        if counts.get(sev, 0) > 0:
            parts.append(f"{counts[sev]} {sev}")
    if parts:
        print(f"Findings:       {', '.join(parts)}")
    else:
        print("Findings:       None - all checks passed!")

    if findings_by_file:
        print(f"\n{'-'*70}")
        for fpath in sorted(findings_by_file):
            short = fpath.replace("priority_variables_transform/", "")
            print(f"\n{short}:")
            for f in sorted(findings_by_file[fpath], key=lambda x: (x.block, x.check)):
                print(f.terminal_line())
                if in_ci:
                    print(f.gh_annotation())

    # Write Markdown summary
    if args.summary_file:
        _write_summary(args.summary_file, "Phase 3", files_checked, blocks_checked,
                       counts, all_findings, args.summary_limit)

    blocking = [
        f for f in all_findings
        if SEVERITY_RANK.get(f.severity, 0) >= fail_rank
    ]
    if blocking:
        print(f"\n{'='*70}")
        print(f"FAILED: {len(blocking)} findings at or above '{args.fail_on}' severity")
        return 1
    else:
        if all_findings:
            print(f"\n{'='*70}")
            print(f"PASSED (with {len(all_findings)} advisory findings below fail threshold)")
        return 0


def _write_summary(path: str, phase: str, files: int, blocks: int,
                   counts: dict[str, int], findings: list[Finding],
                   limit: int) -> None:
    """Write a Markdown summary table for GITHUB_STEP_SUMMARY."""
    lines: list[str] = []
    lines.append(f"## HV-Lint {phase} Results\n")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Files checked | {files} |")
    lines.append(f"| Blocks checked | {blocks} |")
    for sev in ("CRITICAL", "ERROR", "HIGH", "WARNING", "INFO"):
        if counts.get(sev, 0) > 0:
            lines.append(f"| {sev} | {counts[sev]} |")
    lines.append("")
    if findings:
        sorted_findings = sorted(
            findings,
            key=lambda f: (-SEVERITY_RANK.get(f.severity, 0), f.file, f.block, f.check)
        )
        shown = sorted_findings[:limit]
        lines.append(f"### Findings (showing {len(shown)} of {len(findings)})\n")
        lines.append("| Severity | File | Block | Check | Message |")
        lines.append("|----------|------|-------|-------|---------|")
        for f in shown:
            short = f.file.replace("priority_variables_transform/", "")
            msg = f.message.replace("\r", " ").replace("\n", " ").replace("|", "\\|")
            lines.append(f"| {f.severity} | {short} | {f.block} | {f.check} | {msg} |")
        if len(findings) > limit:
            lines.append(
                f"\n> **{len(findings) - limit} additional findings omitted.** "
                f"Re-run with a higher `summary_limit` or check the raw log."
            )
    else:
        lines.append("All checks passed!\n")
    Path(path).write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    sys.exit(main())
