name: Validate yaml syntax in `*-ingest/*.yaml`
on:
  workflow_dispatch:  # Adds "Run workflow" button in Actions tab
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Install dependencies.
        run: uv sync

      - name: Validate */*-ingest*/*.yaml files.
        run: uv run python validate_ingest_yamls.py

  check-phv-dedup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Install dependencies.
        run: uv sync

      - name: Check PHV deduplication
        run: uv run python check_phv_dedup.py
