name: Validate yaml syntax in `*-ingest/*.yaml`
on:
  workflow_dispatch:  # Adds "Run workflow" button in Actions tab
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python.
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry.
        run: pipx install poetry

      - name: Install dependencies.
        run: poetry lock && poetry install

      - name: Validate */*-ingest*/*.yaml files.
        run: poetry run python validate_ingest_yamls.py

  check-phv-dedup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python.
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry.
        run: pipx install poetry

      - name: Install dependencies.
        run: poetry lock && poetry install

      - name: Check PHV deduplication
        run: poetry run python check_phv_dedup.py
